[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
num-bigint = "=0.4.8"
num-traits = "=0.2.19"
ignore = { version = "=0.4.23", default-features = false }
pathdiff = "=0.2.3"
yaml-rust2 = { version = "=0.13.0", default-features = false }
ryu-js = "=1.0.3"
serde_json = { version = "=1.0.151", features = ["preserve_order", "float_roundtrip"] }

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/Orchestration-Maestro/maestro"

[workspace.lints.rust]
unsafe_code = "forbid"
forbidden_lint_groups = "forbid"

[workspace.lints.clippy]
pedantic = { level = "forbid", priority = -1 }
missing_docs_in_private_items = "forbid"
redundant_clone = "forbid"
too_many_arguments = "forbid"
fn_params_excessive_bools = "forbid"
too_many_lines = "forbid"
cognitive_complexity = "forbid"
excessive_nesting = "forbid"
unwrap_used = "forbid"
expect_used = "forbid"
panic = "forbid"
