//! Native typed catalog source emission.
use super::{Catalog, utf16_order};
use crate::{Model, ModelInput};
use std::fmt::Write as _;
use std::{fs, io, path::Path};

/// Instructions shared by generated source files.
const INSTRUCTIONS: &str = "//! Generated by the generate_catalog_data example.\n//! Do not edit manually; run `just models-generate` to update.\n";
/// Encode a provider as an injective, directory-local filename.
fn provider_filename(provider: &str) -> String {
    let mut name = String::from("provider_");
    for byte in provider.bytes() {
        if byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-' {
            name.push(char::from(byte));
        } else {
            let _ = write!(name, "%{byte:02X}");
        }
    }
    name.push_str(".rs");
    name
}
/// Emit the provider modules and registry, then remove obsolete owned modules.
pub(super) fn write_catalog(catalog: &Catalog, destination: &Path) -> io::Result<()> {
    match fs::create_dir(destination) {
        Ok(()) => {}
        Err(error) if error.kind() == io::ErrorKind::AlreadyExists && destination.is_dir() => {}
        Err(error) => return Err(error),
    }
    let mut providers: Vec<_> = catalog.iter().collect();
    providers.sort_by(|(left, _), (right, _)| utf16_order(left, right));
    let mut registry = String::from(INSTRUCTIONS);
    let mut table = String::from(
        "/// Construct one provider registry.\ntype ProviderConstructor = fn() -> indexmap::IndexMap<&'static str, crate::Model>;\n/// Provider constructor table in emitted order.\nconst PROVIDERS: &[(&str, ProviderConstructor)] = &[",
    );
    let mut owned = std::collections::HashSet::new();
    for (index, (provider, models)) in providers.into_iter().enumerate() {
        let filename = provider_filename(provider);
        fs::write(destination.join(&filename), provider_source(models))?;
        let _ = writeln!(
            registry,
            "/// Generated provider descriptors.\n#[path = {filename:?}]\nmod provider_{index};"
        );
        let _ = writeln!(table, "({provider:?}, provider_{index}::models),");
        owned.insert(filename);
    }
    table.push_str("];\n");
    registry.push_str(&table);
    registry.push_str("/// Assemble providers in emitted order.\npub(super) fn models() -> super::models::ModelRegistry {\nPROVIDERS.iter().map(|(key, constructor)| (*key, constructor())).collect()\n}\n");
    fs::write(destination.join("mod.rs"), registry)?;
    for entry in fs::read_dir(destination)? {
        let entry = entry?;
        let filename = entry.file_name();
        if filename.to_str().is_some_and(|name| {
            name.starts_with("provider_")
                && Path::new(name)
                    .extension()
                    .is_some_and(|extension| extension.eq_ignore_ascii_case("rs"))
                && !owned.contains(name)
        }) && entry.file_type()?.is_file()
            && fs::read(entry.path())?.starts_with(INSTRUCTIONS.as_bytes())
        {
            fs::remove_file(entry.path())?;
        }
    }
    Ok(())
}
/// Build one provider's sorted table and typed descriptor constructors.
fn provider_source(models: &indexmap::IndexMap<String, Model>) -> String {
    let mut source = String::from(INSTRUCTIONS);
    let mut table = String::from(
        "/// Construct one model descriptor.\ntype ModelConstructor = fn() -> crate::Model;\n/// Model constructor table in emitted order.\nconst MODELS: &[(&str, ModelConstructor)] = &[\n",
    );
    let mut models: Vec<_> = models.values().collect();
    models.sort_by(|left, right| utf16_order(&left.id, &right.id));
    for (index, model) in models.into_iter().enumerate() {
        let _ = writeln!(table, "({:?}, model_{index}),", model.id);
        let _ = writeln!(
            source,
            "/// Construct a model descriptor.\nfn model_{index}() -> crate::Model {{\n{}\n}}",
            model_expression(model)
        );
    }
    table.push_str("];\n");
    source.push_str(&table);
    source.push_str("/// Assemble this provider's models in emitted order.\npub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {\nMODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()\n}\n");
    source
}
/// Format a finite number, normalizing both zero signs to positive zero.
pub(super) fn number(value: f64) -> String {
    if value == 0.0 {
        return "0.0".into();
    }
    number_text(&format!("{value:?}"))
}
/// Group the digits of an already rendered native numeric literal.
pub(super) fn number_text(text: &str) -> String {
    let boundary = text.find('e').unwrap_or(text.len());
    let mantissa = &text[..boundary];
    let mut result = match mantissa.split_once('.') {
        Some((integer, fraction)) => format!(
            "{}.{}",
            separate_digits(integer, true),
            separate_digits(fraction, false)
        ),
        None => separate_digits(mantissa, true),
    };
    result.push_str(&text[boundary..]);
    result
}
/// Group long native literal digit runs without changing their numeric value.
pub(super) fn separate_digits(text: &str, from_right: bool) -> String {
    if text.len() < 5 {
        return text.into();
    }
    let mut grouped = String::new();
    for (index, character) in text.chars().enumerate() {
        grouped.push(character);
        let offset = if from_right {
            text.len() - index - 1
        } else {
            index + 1
        };
        if character.is_ascii_digit() && index + 1 < text.len() && offset.is_multiple_of(3) {
            grouped.push('_');
        }
    }
    grouped
}
/// Encode an optional ordered string map without normalizing its keys.
fn headers(model: &Model) -> String {
    model.headers.as_ref().map_or_else(
        || "None".into(),
        |headers| {
            let entries = headers
                .iter()
                .map(|(key, value)| format!("({}, {})", string(key), string(value)))
                .collect::<Vec<_>>()
                .join(",");
            format!("Some(indexmap::IndexMap::from([{entries}]))")
        },
    )
}
/// Encode optional thinking entries, retaining absent, null and empty text.
fn thinking(model: &Model) -> String {
    model.thinking_level_map.as_ref().map_or_else(
        || "None".into(),
        |levels| {
            let entries = levels
                .iter()
                .map(|(level, value)| {
                    let value = value
                        .as_ref()
                        .map_or_else(|| "None".into(), |value| format!("Some({})", string(value)));
                    format!("(crate::ModelThinkingLevel::{level:?}, {value})")
                })
                .collect::<Vec<_>>()
                .join(",");
            format!("Some(std::collections::BTreeMap::from([{entries}]))")
        },
    )
}
/// Encode the existing descriptor as a native Rust constructor expression.
pub(super) fn model_expression(model: &Model) -> String {
    let input = model
        .input
        .iter()
        .map(|kind| match kind {
            ModelInput::Text => "crate::ModelInput::Text",
            ModelInput::Image => "crate::ModelInput::Image",
        })
        .collect::<Vec<_>>()
        .join(",");
    format!(
        "crate::Model {{\nid: {},\nname: {},\napi: {},\nprovider: {},\nbase_url: {},\nreasoning: {},\nthinking_level_map: {},\ninput: vec![{}],\ncost: crate::ModelCost {{ input: {}, output: {}, cache_read: {}, cache_write: {} }},\ncontext_window: {},\nmax_tokens: {},\nheaders: {},\ncompat: {},\n}}",
        string(&model.id),
        string(&model.name),
        string(&model.api),
        string(&model.provider),
        string(&model.base_url),
        model.reasoning,
        thinking(model),
        input,
        number(model.cost.input),
        number(model.cost.output),
        number(model.cost.cache_read),
        number(model.cost.cache_write),
        number(model.context_window),
        number(model.max_tokens),
        headers(model),
        super::emit_compat::compat(model.compat.as_ref())
    )
}

/// Encode owned text as a native string construction.
fn string(value: &str) -> String {
    if value.is_empty() {
        "String::new()".into()
    } else {
        format!("{value:?}.into()")
    }
}
