//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Generated provider descriptors.
#[path = "provider_amazon-bedrock.rs"]
mod provider_0;
/// Generated provider descriptors.
#[path = "provider_anthropic.rs"]
mod provider_1;
/// Generated provider descriptors.
#[path = "provider_azure-openai-responses.rs"]
mod provider_2;
/// Generated provider descriptors.
#[path = "provider_cerebras.rs"]
mod provider_3;
/// Generated provider descriptors.
#[path = "provider_cloudflare-ai-gateway.rs"]
mod provider_4;
/// Generated provider descriptors.
#[path = "provider_cloudflare-workers-ai.rs"]
mod provider_5;
/// Generated provider descriptors.
#[path = "provider_deepseek.rs"]
mod provider_6;
/// Generated provider descriptors.
#[path = "provider_fireworks.rs"]
mod provider_7;
/// Generated provider descriptors.
#[path = "provider_github-copilot.rs"]
mod provider_8;
/// Generated provider descriptors.
#[path = "provider_google.rs"]
mod provider_9;
/// Generated provider descriptors.
#[path = "provider_google-vertex.rs"]
mod provider_10;
/// Generated provider descriptors.
#[path = "provider_groq.rs"]
mod provider_11;
/// Generated provider descriptors.
#[path = "provider_huggingface.rs"]
mod provider_12;
/// Generated provider descriptors.
#[path = "provider_kimi-coding.rs"]
mod provider_13;
/// Generated provider descriptors.
#[path = "provider_minimax.rs"]
mod provider_14;
/// Generated provider descriptors.
#[path = "provider_minimax-cn.rs"]
mod provider_15;
/// Generated provider descriptors.
#[path = "provider_mistral.rs"]
mod provider_16;
/// Generated provider descriptors.
#[path = "provider_moonshotai.rs"]
mod provider_17;
/// Generated provider descriptors.
#[path = "provider_moonshotai-cn.rs"]
mod provider_18;
/// Generated provider descriptors.
#[path = "provider_openai.rs"]
mod provider_19;
/// Generated provider descriptors.
#[path = "provider_openai-codex.rs"]
mod provider_20;
/// Generated provider descriptors.
#[path = "provider_opencode.rs"]
mod provider_21;
/// Generated provider descriptors.
#[path = "provider_opencode-go.rs"]
mod provider_22;
/// Generated provider descriptors.
#[path = "provider_openrouter.rs"]
mod provider_23;
/// Generated provider descriptors.
#[path = "provider_vercel-ai-gateway.rs"]
mod provider_24;
/// Generated provider descriptors.
#[path = "provider_xai.rs"]
mod provider_25;
/// Generated provider descriptors.
#[path = "provider_xiaomi.rs"]
mod provider_26;
/// Generated provider descriptors.
#[path = "provider_xiaomi-token-plan-ams.rs"]
mod provider_27;
/// Generated provider descriptors.
#[path = "provider_xiaomi-token-plan-cn.rs"]
mod provider_28;
/// Generated provider descriptors.
#[path = "provider_xiaomi-token-plan-sgp.rs"]
mod provider_29;
/// Generated provider descriptors.
#[path = "provider_zai.rs"]
mod provider_30;
/// Construct one provider registry.
type ProviderConstructor = fn() -> indexmap::IndexMap<&'static str, crate::Model>;
/// Provider constructor table in emitted order.
const PROVIDERS: &[(&str, ProviderConstructor)] = &[("amazon-bedrock", provider_0::models),
("anthropic", provider_1::models),
("azure-openai-responses", provider_2::models),
("cerebras", provider_3::models),
("cloudflare-ai-gateway", provider_4::models),
("cloudflare-workers-ai", provider_5::models),
("deepseek", provider_6::models),
("fireworks", provider_7::models),
("github-copilot", provider_8::models),
("google", provider_9::models),
("google-vertex", provider_10::models),
("groq", provider_11::models),
("huggingface", provider_12::models),
("kimi-coding", provider_13::models),
("minimax", provider_14::models),
("minimax-cn", provider_15::models),
("mistral", provider_16::models),
("moonshotai", provider_17::models),
("moonshotai-cn", provider_18::models),
("openai", provider_19::models),
("openai-codex", provider_20::models),
("opencode", provider_21::models),
("opencode-go", provider_22::models),
("openrouter", provider_23::models),
("vercel-ai-gateway", provider_24::models),
("xai", provider_25::models),
("xiaomi", provider_26::models),
("xiaomi-token-plan-ams", provider_27::models),
("xiaomi-token-plan-cn", provider_28::models),
("xiaomi-token-plan-sgp", provider_29::models),
("zai", provider_30::models),
];
/// Assemble providers in emitted order.
pub(super) fn models() -> super::models::ModelRegistry {
PROVIDERS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
