//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "codestral-latest".into(),
name: "Codestral (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 0.9, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "devstral-2512".into(),
name: "Devstral 2".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "devstral-medium-2507".into(),
name: "Devstral Medium".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "devstral-medium-latest".into(),
name: "Devstral 2 (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "devstral-small-2505".into(),
name: "Devstral Small 2505".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "devstral-small-2507".into(),
name: "Devstral Small".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "labs-devstral-small-2512".into(),
name: "Devstral Small 2".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "magistral-medium-latest".into(),
name: "Magistral Medium (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 5.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "magistral-small".into(),
name: "Magistral Small".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "ministral-3b-latest".into(),
name: "Ministral 3B (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.04, output: 0.04, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "ministral-8b-latest".into(),
name: "Ministral 8B (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.1, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "mistral-large-2411".into(),
name: "Mistral Large 2.1".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "mistral-large-2512".into(),
name: "Mistral Large 3".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "mistral-large-latest".into(),
name: "Mistral Large (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "mistral-medium-2505".into(),
name: "Mistral Medium 3".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "mistral-medium-2508".into(),
name: "Mistral Medium 3.1".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "mistral-medium-2604".into(),
name: "Mistral Medium 3.5".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.5, output: 7.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "mistral-medium-3.5".into(),
name: "Mistral Medium 3.5".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.5, output: 7.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "mistral-medium-latest".into(),
name: "Mistral Medium (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.5, output: 7.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "mistral-nemo".into(),
name: "Mistral Nemo".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "mistral-small-2506".into(),
name: "Mistral Small 3.2".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "mistral-small-2603".into(),
name: "Mistral Small 4".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "mistral-small-latest".into(),
name: "Mistral Small (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "open-mistral-7b".into(),
name: "Mistral 7B".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 0.25, cache_read: 0.0, cache_write: 0.0 },
context_window: 8000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "open-mixtral-8x22b".into(),
name: "Mixtral 8x22B".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 64_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "open-mixtral-8x7b".into(),
name: "Mixtral 8x7B".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.7, output: 0.7, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "pixtral-12b".into(),
name: "Pixtral 12B".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_27() -> crate::Model {
crate::Model {
id: "pixtral-large-latest".into(),
name: "Pixtral Large (latest)".into(),
api: "mistral-conversations".into(),
provider: "mistral".into(),
base_url: "https://api.mistral.ai".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("codestral-latest", model_0),
("devstral-2512", model_1),
("devstral-medium-2507", model_2),
("devstral-medium-latest", model_3),
("devstral-small-2505", model_4),
("devstral-small-2507", model_5),
("labs-devstral-small-2512", model_6),
("magistral-medium-latest", model_7),
("magistral-small", model_8),
("ministral-3b-latest", model_9),
("ministral-8b-latest", model_10),
("mistral-large-2411", model_11),
("mistral-large-2512", model_12),
("mistral-large-latest", model_13),
("mistral-medium-2505", model_14),
("mistral-medium-2508", model_15),
("mistral-medium-2604", model_16),
("mistral-medium-3.5", model_17),
("mistral-medium-latest", model_18),
("mistral-nemo", model_19),
("mistral-small-2506", model_20),
("mistral-small-2603", model_21),
("mistral-small-latest", model_22),
("open-mistral-7b", model_23),
("open-mixtral-8x22b", model_24),
("open-mixtral-8x7b", model_25),
("pixtral-12b", model_26),
("pixtral-large-latest", model_27),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
