//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "kimi-k2-0711-preview".into(),
name: "Kimi K2 0711".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.15, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "kimi-k2-0905-preview".into(),
name: "Kimi K2 0905".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "kimi-k2-thinking".into(),
name: "Kimi K2 Thinking".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "kimi-k2-thinking-turbo".into(),
name: "Kimi K2 Thinking Turbo".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.15, output: 8.0, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "kimi-k2-turbo-preview".into(),
name: "Kimi K2 Turbo".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.4, output: 10.0, cache_read: 0.6, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "kimi-k2.6".into(),
name: "Kimi K2.6".into(),
api: "openai-completions".into(),
provider: "moonshotai".into(),
base_url: "https://api.moonshot.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
supports_strict_mode: Some(false),
max_tokens_field: Some(crate::MaxTokensField::MaxTokens),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("kimi-k2-0711-preview", model_0),
("kimi-k2-0905-preview", model_1),
("kimi-k2-thinking", model_2),
("kimi-k2-thinking-turbo", model_3),
("kimi-k2-turbo-preview", model_4),
("kimi-k2.5", model_5),
("kimi-k2.6", model_6),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
