//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "@cf/google/gemma-4-26b-a4b-it".into(),
name: "Gemma 4 26B A4B IT".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "@cf/meta/llama-4-scout-17b-16e-instruct".into(),
name: "Llama 4 Scout 17B 16E Instruct".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.27, output: 0.85, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "@cf/moonshotai/kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "@cf/moonshotai/kimi-k2.6".into(),
name: "Kimi K2.6".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "@cf/nvidia/nemotron-3-120b-a12b".into(),
name: "Nemotron 3 Super 120B".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "@cf/openai/gpt-oss-120b".into(),
name: "GPT OSS 120B".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.35, output: 0.75, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "@cf/openai/gpt-oss-20b".into(),
name: "GPT OSS 20B".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.2, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "@cf/zai-org/glm-4.7-flash".into(),
name: "GLM-4.7-Flash".into(),
api: "openai-completions".into(),
provider: "cloudflare-workers-ai".into(),
base_url: "https://api.cloudflare.com/client/v4/accounts/{CLOUDFLARE_ACCOUNT_ID}/ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.06, output: 0.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
send_session_affinity_headers: Some(true),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("@cf/google/gemma-4-26b-a4b-it", model_0),
("@cf/meta/llama-4-scout-17b-16e-instruct", model_1),
("@cf/moonshotai/kimi-k2.5", model_2),
("@cf/moonshotai/kimi-k2.6", model_3),
("@cf/nvidia/nemotron-3-120b-a12b", model_4),
("@cf/openai/gpt-oss-120b", model_5),
("@cf/openai/gpt-oss-20b", model_6),
("@cf/zai-org/glm-4.7-flash", model_7),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
