//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/deepseek-v3p1".into(),
name: "DeepSeek V3.1".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.56, output: 1.68, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 163_840.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/deepseek-v3p2".into(),
name: "DeepSeek V3.2".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.56, output: 1.68, cache_read: 0.28, cache_write: 0.0 },
context_window: 160_000.0,
max_tokens: 160_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/deepseek-v4-pro".into(),
name: "DeepSeek V4 Pro".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.74, output: 3.48, cache_read: 0.15, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/glm-4p5".into(),
name: "GLM 4.5".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.55, output: 2.19, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/glm-4p5-air".into(),
name: "GLM 4.5 Air".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 0.88, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/glm-4p7".into(),
name: "GLM 4.7".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.2, cache_read: 0.3, cache_write: 0.0 },
context_window: 198_000.0,
max_tokens: 198_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/glm-5".into(),
name: "GLM 5".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.5, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/glm-5p1".into(),
name: "GLM 5.1".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0 },
context_window: 202_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/gpt-oss-120b".into(),
name: "GPT OSS 120B".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/gpt-oss-20b".into(),
name: "GPT OSS 20B".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.05, output: 0.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/kimi-k2-instruct".into(),
name: "Kimi K2 Instruct".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/kimi-k2-thinking".into(),
name: "Kimi K2 Thinking".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.3, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/kimi-k2p5".into(),
name: "Kimi K2.5".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/kimi-k2p6".into(),
name: "Kimi K2.6".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 262_000.0,
max_tokens: 262_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/minimax-m2p1".into(),
name: "MiniMax-M2.1".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 200_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/minimax-m2p5".into(),
name: "MiniMax-M2.5".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.0 },
context_window: 196_608.0,
max_tokens: 196_608.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/minimax-m2p7".into(),
name: "MiniMax-M2.7".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.0 },
context_window: 196_608.0,
max_tokens: 196_608.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "accounts/fireworks/models/qwen3p6-plus".into(),
name: "Qwen 3.6 Plus".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "accounts/fireworks/routers/kimi-k2p5-turbo".into(),
name: "Kimi K2.5 Turbo".into(),
api: "anthropic-messages".into(),
provider: "fireworks".into(),
base_url: "https://api.fireworks.ai/inference".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("accounts/fireworks/models/deepseek-v3p1", model_0),
("accounts/fireworks/models/deepseek-v3p2", model_1),
("accounts/fireworks/models/deepseek-v4-pro", model_2),
("accounts/fireworks/models/glm-4p5", model_3),
("accounts/fireworks/models/glm-4p5-air", model_4),
("accounts/fireworks/models/glm-4p7", model_5),
("accounts/fireworks/models/glm-5", model_6),
("accounts/fireworks/models/glm-5p1", model_7),
("accounts/fireworks/models/gpt-oss-120b", model_8),
("accounts/fireworks/models/gpt-oss-20b", model_9),
("accounts/fireworks/models/kimi-k2-instruct", model_10),
("accounts/fireworks/models/kimi-k2-thinking", model_11),
("accounts/fireworks/models/kimi-k2p5", model_12),
("accounts/fireworks/models/kimi-k2p6", model_13),
("accounts/fireworks/models/minimax-m2p1", model_14),
("accounts/fireworks/models/minimax-m2p5", model_15),
("accounts/fireworks/models/minimax-m2p7", model_16),
("accounts/fireworks/models/qwen3p6-plus", model_17),
("accounts/fireworks/routers/kimi-k2p5-turbo", model_18),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
