//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "glm-4.5-air".into(),
name: "GLM-4.5-Air".into(),
api: "openai-completions".into(),
provider: "zai".into(),
base_url: "https://api.z.ai/api/coding/paas/v4".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 98_304.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false)),("thinkingFormat".into(), serde_json::Value::String("zai".into()))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "glm-4.7".into(),
name: "GLM-4.7".into(),
api: "openai-completions".into(),
provider: "zai".into(),
base_url: "https://api.z.ai/api/coding/paas/v4".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false)),("thinkingFormat".into(), serde_json::Value::String("zai".into())),("zaiToolStream".into(), serde_json::Value::Bool(true))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "glm-5-turbo".into(),
name: "GLM-5-Turbo".into(),
api: "openai-completions".into(),
provider: "zai".into(),
base_url: "https://api.z.ai/api/coding/paas/v4".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false)),("thinkingFormat".into(), serde_json::Value::String("zai".into())),("zaiToolStream".into(), serde_json::Value::Bool(true))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "glm-5.1".into(),
name: "GLM-5.1".into(),
api: "openai-completions".into(),
provider: "zai".into(),
base_url: "https://api.z.ai/api/coding/paas/v4".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false)),("thinkingFormat".into(), serde_json::Value::String("zai".into())),("zaiToolStream".into(), serde_json::Value::Bool(true))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "glm-5v-turbo".into(),
name: "GLM-5V-Turbo".into(),
api: "openai-completions".into(),
provider: "zai".into(),
base_url: "https://api.z.ai/api/coding/paas/v4".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false)),("thinkingFormat".into(), serde_json::Value::String("zai".into())),("zaiToolStream".into(), serde_json::Value::Bool(true))].into_iter().collect())),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("glm-4.5-air", model_0),
("glm-4.7", model_1),
("glm-5-turbo", model_2),
("glm-5.1", model_3),
("glm-5v-turbo", model_4),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
