//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "claude-3-5-haiku-20241022".into(),
name: "Claude Haiku 3.5".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.8, output: 4.0, cache_read: 0.08, cache_write: 1.0 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "claude-3-5-haiku-latest".into(),
name: "Claude Haiku 3.5 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.8, output: 4.0, cache_read: 0.08, cache_write: 1.0 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "claude-3-5-sonnet-20240620".into(),
name: "Claude Sonnet 3.5".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "claude-3-5-sonnet-20241022".into(),
name: "Claude Sonnet 3.5 v2".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "claude-3-7-sonnet-20250219".into(),
name: "Claude Sonnet 3.7".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "claude-3-haiku-20240307".into(),
name: "Claude Haiku 3".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 1.25, cache_read: 0.03, cache_write: 0.3 },
context_window: 200_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "claude-3-opus-20240229".into(),
name: "Claude Opus 3".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "claude-3-sonnet-20240229".into(),
name: "Claude Sonnet 3".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 0.3 },
context_window: 200_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "claude-haiku-4-5".into(),
name: "Claude Haiku 4.5 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "claude-haiku-4-5-20251001".into(),
name: "Claude Haiku 4.5".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "claude-opus-4-0".into(),
name: "Claude Opus 4 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "claude-opus-4-1".into(),
name: "Claude Opus 4.1 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "claude-opus-4-1-20250805".into(),
name: "Claude Opus 4.1".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "claude-opus-4-20250514".into(),
name: "Claude Opus 4".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "claude-opus-4-5".into(),
name: "Claude Opus 4.5 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "claude-opus-4-5-20251101".into(),
name: "Claude Opus 4.5".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "claude-opus-4-6".into(),
name: "Claude Opus 4.6".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "claude-opus-4-7".into(),
name: "Claude Opus 4.7".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-0".into(),
name: "Claude Sonnet 4 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-20250514".into(),
name: "Claude Sonnet 4".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-5".into(),
name: "Claude Sonnet 4.5 (latest)".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-5-20250929".into(),
name: "Claude Sonnet 4.5".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6".into(),
api: "anthropic-messages".into(),
provider: "anthropic".into(),
base_url: "https://api.anthropic.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("claude-3-5-haiku-20241022", model_0),
("claude-3-5-haiku-latest", model_1),
("claude-3-5-sonnet-20240620", model_2),
("claude-3-5-sonnet-20241022", model_3),
("claude-3-7-sonnet-20250219", model_4),
("claude-3-haiku-20240307", model_5),
("claude-3-opus-20240229", model_6),
("claude-3-sonnet-20240229", model_7),
("claude-haiku-4-5", model_8),
("claude-haiku-4-5-20251001", model_9),
("claude-opus-4-0", model_10),
("claude-opus-4-1", model_11),
("claude-opus-4-1-20250805", model_12),
("claude-opus-4-20250514", model_13),
("claude-opus-4-5", model_14),
("claude-opus-4-5-20251101", model_15),
("claude-opus-4-6", model_16),
("claude-opus-4-7", model_17),
("claude-sonnet-4-0", model_18),
("claude-sonnet-4-20250514", model_19),
("claude-sonnet-4-5", model_20),
("claude-sonnet-4-5-20250929", model_21),
("claude-sonnet-4-6", model_22),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
