//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "deepseek-v4-flash".into(),
name: "DeepSeek V4 Flash".into(),
api: "openai-completions".into(),
provider: "deepseek".into(),
base_url: "https://api.deepseek.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("high".into())),(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.14, output: 0.28, cache_read: 0.0028, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
requires_reasoning_content_on_assistant_messages: Some(true),
thinking_format: Some(crate::ThinkingFormat::Deepseek),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "deepseek-v4-pro".into(),
name: "DeepSeek V4 Pro".into(),
api: "openai-completions".into(),
provider: "deepseek".into(),
base_url: "https://api.deepseek.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("high".into())),(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.435, output: 0.87, cache_read: 0.003_625, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
requires_reasoning_content_on_assistant_messages: Some(true),
thinking_format: Some(crate::ThinkingFormat::Deepseek),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("deepseek-v4-flash", model_0),
("deepseek-v4-pro", model_1),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
