//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "gpt-4".into(),
name: "GPT-4".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 30.0, output: 60.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "gpt-4-turbo".into(),
name: "GPT-4 Turbo".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 10.0, output: 30.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "gpt-4.1".into(),
name: "GPT-4.1".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 8.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "gpt-4.1-mini".into(),
name: "GPT-4.1 mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 1.6, cache_read: 0.1, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "gpt-4.1-nano".into(),
name: "GPT-4.1 nano".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.03, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "gpt-4o".into(),
name: "GPT-4o".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "gpt-4o-2024-05-13".into(),
name: "GPT-4o (2024-05-13)".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 15.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "gpt-4o-2024-08-06".into(),
name: "GPT-4o (2024-08-06)".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "gpt-4o-2024-11-20".into(),
name: "GPT-4o (2024-11-20)".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gpt-4o-mini".into(),
name: "GPT-4o mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.08, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "gpt-5".into(),
name: "GPT-5".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "gpt-5-chat-latest".into(),
name: "GPT-5 Chat Latest".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "gpt-5-codex".into(),
name: "GPT-5-Codex".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "gpt-5-mini".into(),
name: "GPT-5 Mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.025, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "gpt-5-nano".into(),
name: "GPT-5 Nano".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.05, output: 0.4, cache_read: 0.005, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "gpt-5-pro".into(),
name: "GPT-5 Pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 120.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 272_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "gpt-5.1".into(),
name: "GPT-5.1".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.13, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "gpt-5.1-chat-latest".into(),
name: "GPT-5.1 Chat".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex".into(),
name: "GPT-5.1 Codex".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-max".into(),
name: "GPT-5.1 Codex Max".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-mini".into(),
name: "GPT-5.1 Codex mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.025, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "gpt-5.2".into(),
name: "GPT-5.2".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "gpt-5.2-chat-latest".into(),
name: "GPT-5.2 Chat".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "gpt-5.2-codex".into(),
name: "GPT-5.2 Codex".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "gpt-5.2-pro".into(),
name: "GPT-5.2 Pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 21.0, output: 168.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "gpt-5.3-chat-latest".into(),
name: "GPT-5.3 Chat (latest)".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: false,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex".into(),
name: "GPT-5.3 Codex".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_27() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex-spark".into(),
name: "GPT-5.3 Codex Spark".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_28() -> crate::Model {
crate::Model {
id: "gpt-5.4".into(),
name: "GPT-5.4".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 15.0, cache_read: 0.25, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_29() -> crate::Model {
crate::Model {
id: "gpt-5.4-mini".into(),
name: "GPT-5.4 mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.75, output: 4.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_30() -> crate::Model {
crate::Model {
id: "gpt-5.4-nano".into(),
name: "GPT-5.4 nano".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 1.25, cache_read: 0.02, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_31() -> crate::Model {
crate::Model {
id: "gpt-5.4-pro".into(),
name: "GPT-5.4 Pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_32() -> crate::Model {
crate::Model {
id: "gpt-5.5".into(),
name: "GPT-5.5".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 30.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_33() -> crate::Model {
crate::Model {
id: "gpt-5.5-pro".into(),
name: "GPT-5.5 Pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_34() -> crate::Model {
crate::Model {
id: "o1".into(),
name: "o1".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 60.0, cache_read: 7.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_35() -> crate::Model {
crate::Model {
id: "o1-pro".into(),
name: "o1-pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 150.0, output: 600.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_36() -> crate::Model {
crate::Model {
id: "o3".into(),
name: "o3".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 8.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_37() -> crate::Model {
crate::Model {
id: "o3-deep-research".into(),
name: "o3-deep-research".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 10.0, output: 40.0, cache_read: 2.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_38() -> crate::Model {
crate::Model {
id: "o3-mini".into(),
name: "o3-mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.1, output: 4.4, cache_read: 0.55, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_39() -> crate::Model {
crate::Model {
id: "o3-pro".into(),
name: "o3-pro".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 20.0, output: 80.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_40() -> crate::Model {
crate::Model {
id: "o4-mini".into(),
name: "o4-mini".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.1, output: 4.4, cache_read: 0.28, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_41() -> crate::Model {
crate::Model {
id: "o4-mini-deep-research".into(),
name: "o4-mini-deep-research".into(),
api: "openai-responses".into(),
provider: "openai".into(),
base_url: "https://api.openai.com/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 8.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("gpt-4", model_0),
("gpt-4-turbo", model_1),
("gpt-4.1", model_2),
("gpt-4.1-mini", model_3),
("gpt-4.1-nano", model_4),
("gpt-4o", model_5),
("gpt-4o-2024-05-13", model_6),
("gpt-4o-2024-08-06", model_7),
("gpt-4o-2024-11-20", model_8),
("gpt-4o-mini", model_9),
("gpt-5", model_10),
("gpt-5-chat-latest", model_11),
("gpt-5-codex", model_12),
("gpt-5-mini", model_13),
("gpt-5-nano", model_14),
("gpt-5-pro", model_15),
("gpt-5.1", model_16),
("gpt-5.1-chat-latest", model_17),
("gpt-5.1-codex", model_18),
("gpt-5.1-codex-max", model_19),
("gpt-5.1-codex-mini", model_20),
("gpt-5.2", model_21),
("gpt-5.2-chat-latest", model_22),
("gpt-5.2-codex", model_23),
("gpt-5.2-pro", model_24),
("gpt-5.3-chat-latest", model_25),
("gpt-5.3-codex", model_26),
("gpt-5.3-codex-spark", model_27),
("gpt-5.4", model_28),
("gpt-5.4-mini", model_29),
("gpt-5.4-nano", model_30),
("gpt-5.4-pro", model_31),
("gpt-5.5", model_32),
("gpt-5.5-pro", model_33),
("o1", model_34),
("o1-pro", model_35),
("o3", model_36),
("o3-deep-research", model_37),
("o3-mini", model_38),
("o3-pro", model_39),
("o4-mini", model_40),
("o4-mini-deep-research", model_41),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
