//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "gpt-oss-120b".into(),
name: "GPT OSS 120B".into(),
api: "openai-completions".into(),
provider: "cerebras".into(),
base_url: "https://api.cerebras.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 0.69, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "llama3.1-8b".into(),
name: "Llama 3.1 8B".into(),
api: "openai-completions".into(),
provider: "cerebras".into(),
base_url: "https://api.cerebras.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.1, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "qwen-3-235b-a22b-instruct-2507".into(),
name: "Qwen 3 235B Instruct".into(),
api: "openai-completions".into(),
provider: "cerebras".into(),
base_url: "https://api.cerebras.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "zai-glm-4.7".into(),
name: "Z.AI GLM-4.7".into(),
api: "openai-completions".into(),
provider: "cerebras".into(),
base_url: "https://api.cerebras.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.25, output: 2.75, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 40_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("gpt-oss-120b", model_0),
("llama3.1-8b", model_1),
("qwen-3-235b-a22b-instruct-2507", model_2),
("zai-glm-4.7", model_3),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
