//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "gemini-1.5-flash".into(),
name: "Gemini 1.5 Flash".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.018_75, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "gemini-1.5-flash-8b".into(),
name: "Gemini 1.5 Flash-8B".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0375, output: 0.15, cache_read: 0.01, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "gemini-1.5-pro".into(),
name: "Gemini 1.5 Pro".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 5.0, cache_read: 0.3125, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "gemini-2.0-flash".into(),
name: "Gemini 2.0 Flash".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.025, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "gemini-2.0-flash-lite".into(),
name: "Gemini 2.0 Flash Lite".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash".into(),
name: "Gemini 2.5 Flash".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 2.5, cache_read: 0.03, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-lite".into(),
name: "Gemini 2.5 Flash Lite".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.025, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-lite-preview-06-17".into(),
name: "Gemini 2.5 Flash Lite Preview 06-17".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.025, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-lite-preview-09-2025".into(),
name: "Gemini 2.5 Flash Lite Preview 09-25".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.025, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-preview-04-17".into(),
name: "Gemini 2.5 Flash Preview 04-17".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0375, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-preview-05-20".into(),
name: "Gemini 2.5 Flash Preview 05-20".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0375, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-preview-09-2025".into(),
name: "Gemini 2.5 Flash Preview 09-25".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 2.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "gemini-2.5-pro".into(),
name: "Gemini 2.5 Pro".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "gemini-2.5-pro-preview-05-06".into(),
name: "Gemini 2.5 Pro Preview 05-06".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.31, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "gemini-2.5-pro-preview-06-05".into(),
name: "Gemini 2.5 Pro Preview 06-05".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.31, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "gemini-3-flash-preview".into(),
name: "Gemini 3 Flash Preview".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "gemini-3-pro-preview".into(),
name: "Gemini 3 Pro Preview".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "gemini-3.1-flash-lite-preview".into(),
name: "Gemini 3.1 Flash Lite Preview".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 1.5, cache_read: 0.025, cache_write: 1.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro-preview".into(),
name: "Gemini 3.1 Pro Preview".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro-preview-customtools".into(),
name: "Gemini 3.1 Pro Preview Custom Tools".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "gemini-flash-latest".into(),
name: "Gemini Flash Latest".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 2.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "gemini-flash-lite-latest".into(),
name: "Gemini Flash-Lite Latest".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.025, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "gemini-live-2.5-flash".into(),
name: "Gemini Live 2.5 Flash".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "gemini-live-2.5-flash-preview-native-audio".into(),
name: "Gemini Live 2.5 Flash Preview Native Audio".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.5, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "gemma-3-27b-it".into(),
name: "Gemma 3 27B".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "gemma-4-26b-a4b-it".into(),
name: "Gemma 4 26B".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, Some("MINIMAL".into())),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "gemma-4-31b-it".into(),
name: "Gemma 4 31B".into(),
api: "google-generative-ai".into(),
provider: "google".into(),
base_url: "https://generativelanguage.googleapis.com/v1beta".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, Some("MINIMAL".into())),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("gemini-1.5-flash", model_0),
("gemini-1.5-flash-8b", model_1),
("gemini-1.5-pro", model_2),
("gemini-2.0-flash", model_3),
("gemini-2.0-flash-lite", model_4),
("gemini-2.5-flash", model_5),
("gemini-2.5-flash-lite", model_6),
("gemini-2.5-flash-lite-preview-06-17", model_7),
("gemini-2.5-flash-lite-preview-09-2025", model_8),
("gemini-2.5-flash-preview-04-17", model_9),
("gemini-2.5-flash-preview-05-20", model_10),
("gemini-2.5-flash-preview-09-2025", model_11),
("gemini-2.5-pro", model_12),
("gemini-2.5-pro-preview-05-06", model_13),
("gemini-2.5-pro-preview-06-05", model_14),
("gemini-3-flash-preview", model_15),
("gemini-3-pro-preview", model_16),
("gemini-3.1-flash-lite-preview", model_17),
("gemini-3.1-pro-preview", model_18),
("gemini-3.1-pro-preview-customtools", model_19),
("gemini-flash-latest", model_20),
("gemini-flash-lite-latest", model_21),
("gemini-live-2.5-flash", model_22),
("gemini-live-2.5-flash-preview-native-audio", model_23),
("gemma-3-27b-it", model_24),
("gemma-4-26b-a4b-it", model_25),
("gemma-4-31b-it", model_26),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
