//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "MiniMaxAI/MiniMax-M2.1".into(),
name: "MiniMax-M2.1".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "MiniMaxAI/MiniMax-M2.5".into(),
name: "MiniMax-M2.5".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "MiniMaxAI/MiniMax-M2.7".into(),
name: "MiniMax-M2.7".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3-235B-A22B-Thinking-2507".into(),
name: "Qwen3-235B-A22B-Thinking-2507".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3-Coder-480B-A35B-Instruct".into(),
name: "Qwen3-Coder-480B-A35B-Instruct".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 66_536.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3-Coder-Next".into(),
name: "Qwen3-Coder-Next".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.2, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3-Next-80B-A3B-Instruct".into(),
name: "Qwen3-Next-80B-A3B-Instruct".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 1.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 66_536.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3-Next-80B-A3B-Thinking".into(),
name: "Qwen3-Next-80B-A3B-Thinking".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "Qwen/Qwen3.5-397B-A17B".into(),
name: "Qwen3.5-397B-A17B".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_768.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "XiaomiMiMo/MiMo-V2-Flash".into(),
name: "MiMo-V2-Flash".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 4096.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "deepseek-ai/DeepSeek-R1-0528".into(),
name: "DeepSeek-R1-0528".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 3.0, output: 5.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 163_840.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "deepseek-ai/DeepSeek-V3.2".into(),
name: "DeepSeek-V3.2".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.28, output: 0.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 65_536.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "deepseek-ai/DeepSeek-V4-Pro".into(),
name: "DeepSeek V4 Pro".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.74, output: 3.48, cache_read: 0.145, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 393_216.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "moonshotai/Kimi-K2-Instruct".into(),
name: "Kimi-K2-Instruct".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "moonshotai/Kimi-K2-Instruct-0905".into(),
name: "Kimi-K2-Instruct-0905".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 16_384.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "moonshotai/Kimi-K2-Thinking".into(),
name: "Kimi-K2-Thinking".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "moonshotai/Kimi-K2.5".into(),
name: "Kimi-K2.5".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "moonshotai/Kimi-K2.6".into(),
name: "Kimi-K2.6".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 262_144.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "zai-org/GLM-4.7".into(),
name: "GLM-4.7".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.2, cache_read: 0.11, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "zai-org/GLM-4.7-Flash".into(),
name: "GLM-4.7-Flash".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 128_000.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "zai-org/GLM-5".into(),
name: "GLM-5".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.2, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "zai-org/GLM-5.1".into(),
name: "GLM-5.1".into(),
api: "openai-completions".into(),
provider: "huggingface".into(),
base_url: "https://router.huggingface.co/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.2, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 131_072.0,
headers: None,
compat: Some(crate::ModelCompat([("supportsDeveloperRole".into(), serde_json::Value::Bool(false))].into_iter().collect())),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("MiniMaxAI/MiniMax-M2.1", model_0),
("MiniMaxAI/MiniMax-M2.5", model_1),
("MiniMaxAI/MiniMax-M2.7", model_2),
("Qwen/Qwen3-235B-A22B-Thinking-2507", model_3),
("Qwen/Qwen3-Coder-480B-A35B-Instruct", model_4),
("Qwen/Qwen3-Coder-Next", model_5),
("Qwen/Qwen3-Next-80B-A3B-Instruct", model_6),
("Qwen/Qwen3-Next-80B-A3B-Thinking", model_7),
("Qwen/Qwen3.5-397B-A17B", model_8),
("XiaomiMiMo/MiMo-V2-Flash", model_9),
("deepseek-ai/DeepSeek-R1-0528", model_10),
("deepseek-ai/DeepSeek-V3.2", model_11),
("deepseek-ai/DeepSeek-V4-Pro", model_12),
("moonshotai/Kimi-K2-Instruct", model_13),
("moonshotai/Kimi-K2-Instruct-0905", model_14),
("moonshotai/Kimi-K2-Thinking", model_15),
("moonshotai/Kimi-K2.5", model_16),
("moonshotai/Kimi-K2.6", model_17),
("zai-org/GLM-4.7", model_18),
("zai-org/GLM-4.7-Flash", model_19),
("zai-org/GLM-5", model_20),
("zai-org/GLM-5.1", model_21),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
