//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "deepseek-r1-distill-llama-70b".into(),
name: "DeepSeek R1 Distill Llama 70B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.75, output: 0.99, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "gemma2-9b-it".into(),
name: "Gemma 2 9B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.2, output: 0.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "groq/compound".into(),
name: "Compound".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "groq/compound-mini".into(),
name: "Compound Mini".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "llama-3.1-8b-instant".into(),
name: "Llama 3.1 8B Instant".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.05, output: 0.08, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "llama-3.3-70b-versatile".into(),
name: "Llama 3.3 70B Versatile".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.59, output: 0.79, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "llama3-70b-8192".into(),
name: "Llama 3 70B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.59, output: 0.79, cache_read: 0.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "llama3-8b-8192".into(),
name: "Llama 3 8B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.05, output: 0.08, cache_read: 0.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "meta-llama/llama-4-maverick-17b-128e-instruct".into(),
name: "Llama 4 Maverick 17B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "meta-llama/llama-4-scout-17b-16e-instruct".into(),
name: "Llama 4 Scout 17B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.11, output: 0.34, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "mistral-saba-24b".into(),
name: "Mistral Saba 24B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.79, output: 0.79, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_768.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2-instruct".into(),
name: "Kimi K2 Instruct".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2-instruct-0905".into(),
name: "Kimi K2 Instruct 0905".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "openai/gpt-oss-120b".into(),
name: "GPT OSS 120B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "openai/gpt-oss-20b".into(),
name: "GPT OSS 20B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "openai/gpt-oss-safeguard-20b".into(),
name: "Safety GPT OSS 20B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.037, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "qwen-qwq-32b".into(),
name: "Qwen QwQ 32B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.29, output: 0.39, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "qwen/qwen3-32b".into(),
name: "Qwen3 32B".into(),
api: "openai-completions".into(),
provider: "groq".into(),
base_url: "https://api.groq.com/openai/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("default".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.29, output: 0.59, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 40_960.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("deepseek-r1-distill-llama-70b", model_0),
("gemma2-9b-it", model_1),
("groq/compound", model_2),
("groq/compound-mini", model_3),
("llama-3.1-8b-instant", model_4),
("llama-3.3-70b-versatile", model_5),
("llama3-70b-8192", model_6),
("llama3-8b-8192", model_7),
("meta-llama/llama-4-maverick-17b-128e-instruct", model_8),
("meta-llama/llama-4-scout-17b-16e-instruct", model_9),
("mistral-saba-24b", model_10),
("moonshotai/kimi-k2-instruct", model_11),
("moonshotai/kimi-k2-instruct-0905", model_12),
("openai/gpt-oss-120b", model_13),
("openai/gpt-oss-20b", model_14),
("openai/gpt-oss-safeguard-20b", model_15),
("qwen-qwq-32b", model_16),
("qwen/qwen3-32b", model_17),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
