//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "gpt-5.1".into(),
name: "GPT-5.1".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-max".into(),
name: "GPT-5.1 Codex Max".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-mini".into(),
name: "GPT-5.1 Codex Mini".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("medium".into())),(crate::ModelThinkingLevel::Low, Some("medium".into())),(crate::ModelThinkingLevel::Medium, Some("medium".into())),(crate::ModelThinkingLevel::High, Some("high".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.025, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "gpt-5.2".into(),
name: "GPT-5.2".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "gpt-5.2-codex".into(),
name: "GPT-5.2 Codex".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex".into(),
name: "GPT-5.3 Codex".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex-spark".into(),
name: "GPT-5.3 Codex Spark".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "gpt-5.4".into(),
name: "GPT-5.4".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 15.0, cache_read: 0.25, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "gpt-5.4-mini".into(),
name: "GPT-5.4 Mini".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.75, output: 4.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gpt-5.5".into(),
name: "GPT-5.5".into(),
api: "openai-codex-responses".into(),
provider: "openai-codex".into(),
base_url: "https://chatgpt.com/backend-api".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, Some("low".into())),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 30.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("gpt-5.1", model_0),
("gpt-5.1-codex-max", model_1),
("gpt-5.1-codex-mini", model_2),
("gpt-5.2", model_3),
("gpt-5.2-codex", model_4),
("gpt-5.3-codex", model_5),
("gpt-5.3-codex-spark", model_6),
("gpt-5.4", model_7),
("gpt-5.4-mini", model_8),
("gpt-5.5", model_9),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
