//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "amazon.nova-2-lite-v1:0".into(),
name: "Nova 2 Lite".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.33, output: 2.75, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "amazon.nova-lite-v1:0".into(),
name: "Nova Lite".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.06, output: 0.24, cache_read: 0.015, cache_write: 0.0 },
context_window: 300_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "amazon.nova-micro-v1:0".into(),
name: "Nova Micro".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.035, output: 0.14, cache_read: 0.008_75, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "amazon.nova-premier-v1:0".into(),
name: "Nova Premier".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 12.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "amazon.nova-pro-v1:0".into(),
name: "Nova Pro".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.8, output: 3.2, cache_read: 0.2, cache_write: 0.0 },
context_window: 300_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "anthropic.claude-3-5-haiku-20241022-v1:0".into(),
name: "Claude Haiku 3.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.8, output: 4.0, cache_read: 0.08, cache_write: 1.0 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "anthropic.claude-3-5-sonnet-20240620-v1:0".into(),
name: "Claude Sonnet 3.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "anthropic.claude-3-5-sonnet-20241022-v2:0".into(),
name: "Claude Sonnet 3.5 v2".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "anthropic.claude-3-7-sonnet-20250219-v1:0".into(),
name: "Claude Sonnet 3.7".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "anthropic.claude-3-haiku-20240307-v1:0".into(),
name: "Claude Haiku 3".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 1.25, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "anthropic.claude-haiku-4-5-20251001-v1:0".into(),
name: "Claude Haiku 4.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "anthropic.claude-opus-4-1-20250805-v1:0".into(),
name: "Claude Opus 4.1".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "anthropic.claude-opus-4-20250514-v1:0".into(),
name: "Claude Opus 4".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "anthropic.claude-opus-4-5-20251101-v1:0".into(),
name: "Claude Opus 4.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "anthropic.claude-opus-4-6-v1".into(),
name: "Claude Opus 4.6".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "anthropic.claude-opus-4-7".into(),
name: "Claude Opus 4.7".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "anthropic.claude-sonnet-4-20250514-v1:0".into(),
name: "Claude Sonnet 4".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "anthropic.claude-sonnet-4-5-20250929-v1:0".into(),
name: "Claude Sonnet 4.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "anthropic.claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "au.anthropic.claude-opus-4-6-v1".into(),
name: "AU Anthropic Claude Opus 4.6".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 16.5, output: 82.5, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "au.anthropic.claude-sonnet-4-6".into(),
name: "AU Anthropic Claude Sonnet 4.6".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.3, output: 16.5, cache_read: 0.33, cache_write: 4.125 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "deepseek.r1-v1:0".into(),
name: "DeepSeek-R1".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.35, output: 5.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "deepseek.v3-v1:0".into(),
name: "DeepSeek-V3.1".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.58, output: 1.68, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 81_920.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "deepseek.v3.2".into(),
name: "DeepSeek-V3.2".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.62, output: 1.85, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 81_920.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
name: "Claude Haiku 4.5 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-opus-4-5-20251101-v1:0".into(),
name: "Claude Opus 4.5 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-opus-4-6-v1".into(),
name: "Claude Opus 4.6 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_27() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-opus-4-7".into(),
name: "Claude Opus 4.7 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_28() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-sonnet-4-20250514-v1:0".into(),
name: "Claude Sonnet 4 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_29() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0".into(),
name: "Claude Sonnet 4.5 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_30() -> crate::Model {
crate::Model {
id: "eu.anthropic.claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6 (EU)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.eu-central-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_31() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
name: "Claude Haiku 4.5 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_32() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-opus-4-5-20251101-v1:0".into(),
name: "Claude Opus 4.5 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_33() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-opus-4-6-v1".into(),
name: "Claude Opus 4.6 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_34() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-opus-4-7".into(),
name: "Claude Opus 4.7 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_35() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-sonnet-4-20250514-v1:0".into(),
name: "Claude Sonnet 4 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_36() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-sonnet-4-5-20250929-v1:0".into(),
name: "Claude Sonnet 4.5 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_37() -> crate::Model {
crate::Model {
id: "global.anthropic.claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6 (Global)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_38() -> crate::Model {
crate::Model {
id: "google.gemma-3-27b-it".into(),
name: "Google Gemma 3 27B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.12, output: 0.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_39() -> crate::Model {
crate::Model {
id: "google.gemma-3-4b-it".into(),
name: "Gemma 3 4B IT".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.04, output: 0.08, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_40() -> crate::Model {
crate::Model {
id: "meta.llama3-1-405b-instruct-v1:0".into(),
name: "Llama 3.1 405B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.4, output: 2.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_41() -> crate::Model {
crate::Model {
id: "meta.llama3-1-70b-instruct-v1:0".into(),
name: "Llama 3.1 70B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_42() -> crate::Model {
crate::Model {
id: "meta.llama3-1-8b-instruct-v1:0".into(),
name: "Llama 3.1 8B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 0.22, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_43() -> crate::Model {
crate::Model {
id: "meta.llama3-2-11b-instruct-v1:0".into(),
name: "Llama 3.2 11B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.16, output: 0.16, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_44() -> crate::Model {
crate::Model {
id: "meta.llama3-2-1b-instruct-v1:0".into(),
name: "Llama 3.2 1B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.1, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_45() -> crate::Model {
crate::Model {
id: "meta.llama3-2-3b-instruct-v1:0".into(),
name: "Llama 3.2 3B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_46() -> crate::Model {
crate::Model {
id: "meta.llama3-2-90b-instruct-v1:0".into(),
name: "Llama 3.2 90B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_47() -> crate::Model {
crate::Model {
id: "meta.llama3-3-70b-instruct-v1:0".into(),
name: "Llama 3.3 70B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_48() -> crate::Model {
crate::Model {
id: "meta.llama4-maverick-17b-instruct-v1:0".into(),
name: "Llama 4 Maverick 17B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.24, output: 0.97, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_49() -> crate::Model {
crate::Model {
id: "meta.llama4-scout-17b-instruct-v1:0".into(),
name: "Llama 4 Scout 17B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.17, output: 0.66, cache_read: 0.0, cache_write: 0.0 },
context_window: 3_500_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_50() -> crate::Model {
crate::Model {
id: "minimax.minimax-m2".into(),
name: "MiniMax M2".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_608.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_51() -> crate::Model {
crate::Model {
id: "minimax.minimax-m2.1".into(),
name: "MiniMax M2.1".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_52() -> crate::Model {
crate::Model {
id: "minimax.minimax-m2.5".into(),
name: "MiniMax M2.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 196_608.0,
max_tokens: 98_304.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_53() -> crate::Model {
crate::Model {
id: "mistral.devstral-2-123b".into(),
name: "Devstral 2 123B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_54() -> crate::Model {
crate::Model {
id: "mistral.magistral-small-2509".into(),
name: "Magistral Small 1.2".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 40_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_55() -> crate::Model {
crate::Model {
id: "mistral.ministral-3-14b-instruct".into(),
name: "Ministral 14B 3.0".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.2, output: 0.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_56() -> crate::Model {
crate::Model {
id: "mistral.ministral-3-3b-instruct".into(),
name: "Ministral 3 3B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.1, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_57() -> crate::Model {
crate::Model {
id: "mistral.ministral-3-8b-instruct".into(),
name: "Ministral 3 8B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_58() -> crate::Model {
crate::Model {
id: "mistral.mistral-large-3-675b-instruct".into(),
name: "Mistral Large 3".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_59() -> crate::Model {
crate::Model {
id: "mistral.pixtral-large-2502-v1:0".into(),
name: "Pixtral Large (25.02)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_60() -> crate::Model {
crate::Model {
id: "mistral.voxtral-mini-3b-2507".into(),
name: "Voxtral Mini 3B 2507".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.04, output: 0.04, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_61() -> crate::Model {
crate::Model {
id: "mistral.voxtral-small-24b-2507".into(),
name: "Voxtral Small 24B 2507".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.35, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_62() -> crate::Model {
crate::Model {
id: "moonshot.kimi-k2-thinking".into(),
name: "Kimi K2 Thinking".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_63() -> crate::Model {
crate::Model {
id: "moonshotai.kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_64() -> crate::Model {
crate::Model {
id: "nvidia.nemotron-nano-12b-v2".into(),
name: "NVIDIA Nemotron Nano 12B v2 VL BF16".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_65() -> crate::Model {
crate::Model {
id: "nvidia.nemotron-nano-3-30b".into(),
name: "NVIDIA Nemotron Nano 3 30B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.06, output: 0.24, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_66() -> crate::Model {
crate::Model {
id: "nvidia.nemotron-nano-9b-v2".into(),
name: "NVIDIA Nemotron Nano 9B v2".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.06, output: 0.23, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_67() -> crate::Model {
crate::Model {
id: "nvidia.nemotron-super-3-120b".into(),
name: "NVIDIA Nemotron 3 Super 120B A12B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.65, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_68() -> crate::Model {
crate::Model {
id: "openai.gpt-oss-120b-1:0".into(),
name: "gpt-oss-120b".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_69() -> crate::Model {
crate::Model {
id: "openai.gpt-oss-20b-1:0".into(),
name: "gpt-oss-20b".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.07, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_70() -> crate::Model {
crate::Model {
id: "openai.gpt-oss-safeguard-120b".into(),
name: "GPT OSS Safeguard 120B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_71() -> crate::Model {
crate::Model {
id: "openai.gpt-oss-safeguard-20b".into(),
name: "GPT OSS Safeguard 20B".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.07, output: 0.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_72() -> crate::Model {
crate::Model {
id: "qwen.qwen3-235b-a22b-2507-v1:0".into(),
name: "Qwen3 235B A22B 2507".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 0.88, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_73() -> crate::Model {
crate::Model {
id: "qwen.qwen3-32b-v1:0".into(),
name: "Qwen3 32B (dense)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 16_384.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_74() -> crate::Model {
crate::Model {
id: "qwen.qwen3-coder-30b-a3b-v1:0".into(),
name: "Qwen3 Coder 30B A3B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_75() -> crate::Model {
crate::Model {
id: "qwen.qwen3-coder-480b-a35b-v1:0".into(),
name: "Qwen3 Coder 480B A35B Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 1.8, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_76() -> crate::Model {
crate::Model {
id: "qwen.qwen3-coder-next".into(),
name: "Qwen3 Coder Next".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 1.8, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_77() -> crate::Model {
crate::Model {
id: "qwen.qwen3-next-80b-a3b".into(),
name: "Qwen/Qwen3-Next-80B-A3B-Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.14, output: 1.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_000.0,
max_tokens: 262_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_78() -> crate::Model {
crate::Model {
id: "qwen.qwen3-vl-235b-a22b".into(),
name: "Qwen/Qwen3-VL-235B-A22B-Instruct".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 1.5, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_000.0,
max_tokens: 262_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_79() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-haiku-4-5-20251001-v1:0".into(),
name: "Claude Haiku 4.5 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_80() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-opus-4-1-20250805-v1:0".into(),
name: "Claude Opus 4.1 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_81() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-opus-4-20250514-v1:0".into(),
name: "Claude Opus 4 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_82() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-opus-4-5-20251101-v1:0".into(),
name: "Claude Opus 4.5 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_83() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-opus-4-6-v1".into(),
name: "Claude Opus 4.6 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_84() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-opus-4-7".into(),
name: "Claude Opus 4.7 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_85() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-sonnet-4-20250514-v1:0".into(),
name: "Claude Sonnet 4 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_86() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-sonnet-4-5-20250929-v1:0".into(),
name: "Claude Sonnet 4.5 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_87() -> crate::Model {
crate::Model {
id: "us.anthropic.claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6 (US)".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_88() -> crate::Model {
crate::Model {
id: "writer.palmyra-x4-v1:0".into(),
name: "Palmyra X4".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 122_880.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_89() -> crate::Model {
crate::Model {
id: "writer.palmyra-x5-v1:0".into(),
name: "Palmyra X5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_040_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_90() -> crate::Model {
crate::Model {
id: "zai.glm-4.7".into(),
name: "GLM-4.7".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_91() -> crate::Model {
crate::Model {
id: "zai.glm-4.7-flash".into(),
name: "GLM-4.7-Flash".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.07, output: 0.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_92() -> crate::Model {
crate::Model {
id: "zai.glm-5".into(),
name: "GLM-5".into(),
api: "bedrock-converse-stream".into(),
provider: "amazon-bedrock".into(),
base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 101_376.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("amazon.nova-2-lite-v1:0", model_0),
("amazon.nova-lite-v1:0", model_1),
("amazon.nova-micro-v1:0", model_2),
("amazon.nova-premier-v1:0", model_3),
("amazon.nova-pro-v1:0", model_4),
("anthropic.claude-3-5-haiku-20241022-v1:0", model_5),
("anthropic.claude-3-5-sonnet-20240620-v1:0", model_6),
("anthropic.claude-3-5-sonnet-20241022-v2:0", model_7),
("anthropic.claude-3-7-sonnet-20250219-v1:0", model_8),
("anthropic.claude-3-haiku-20240307-v1:0", model_9),
("anthropic.claude-haiku-4-5-20251001-v1:0", model_10),
("anthropic.claude-opus-4-1-20250805-v1:0", model_11),
("anthropic.claude-opus-4-20250514-v1:0", model_12),
("anthropic.claude-opus-4-5-20251101-v1:0", model_13),
("anthropic.claude-opus-4-6-v1", model_14),
("anthropic.claude-opus-4-7", model_15),
("anthropic.claude-sonnet-4-20250514-v1:0", model_16),
("anthropic.claude-sonnet-4-5-20250929-v1:0", model_17),
("anthropic.claude-sonnet-4-6", model_18),
("au.anthropic.claude-opus-4-6-v1", model_19),
("au.anthropic.claude-sonnet-4-6", model_20),
("deepseek.r1-v1:0", model_21),
("deepseek.v3-v1:0", model_22),
("deepseek.v3.2", model_23),
("eu.anthropic.claude-haiku-4-5-20251001-v1:0", model_24),
("eu.anthropic.claude-opus-4-5-20251101-v1:0", model_25),
("eu.anthropic.claude-opus-4-6-v1", model_26),
("eu.anthropic.claude-opus-4-7", model_27),
("eu.anthropic.claude-sonnet-4-20250514-v1:0", model_28),
("eu.anthropic.claude-sonnet-4-5-20250929-v1:0", model_29),
("eu.anthropic.claude-sonnet-4-6", model_30),
("global.anthropic.claude-haiku-4-5-20251001-v1:0", model_31),
("global.anthropic.claude-opus-4-5-20251101-v1:0", model_32),
("global.anthropic.claude-opus-4-6-v1", model_33),
("global.anthropic.claude-opus-4-7", model_34),
("global.anthropic.claude-sonnet-4-20250514-v1:0", model_35),
("global.anthropic.claude-sonnet-4-5-20250929-v1:0", model_36),
("global.anthropic.claude-sonnet-4-6", model_37),
("google.gemma-3-27b-it", model_38),
("google.gemma-3-4b-it", model_39),
("meta.llama3-1-405b-instruct-v1:0", model_40),
("meta.llama3-1-70b-instruct-v1:0", model_41),
("meta.llama3-1-8b-instruct-v1:0", model_42),
("meta.llama3-2-11b-instruct-v1:0", model_43),
("meta.llama3-2-1b-instruct-v1:0", model_44),
("meta.llama3-2-3b-instruct-v1:0", model_45),
("meta.llama3-2-90b-instruct-v1:0", model_46),
("meta.llama3-3-70b-instruct-v1:0", model_47),
("meta.llama4-maverick-17b-instruct-v1:0", model_48),
("meta.llama4-scout-17b-instruct-v1:0", model_49),
("minimax.minimax-m2", model_50),
("minimax.minimax-m2.1", model_51),
("minimax.minimax-m2.5", model_52),
("mistral.devstral-2-123b", model_53),
("mistral.magistral-small-2509", model_54),
("mistral.ministral-3-14b-instruct", model_55),
("mistral.ministral-3-3b-instruct", model_56),
("mistral.ministral-3-8b-instruct", model_57),
("mistral.mistral-large-3-675b-instruct", model_58),
("mistral.pixtral-large-2502-v1:0", model_59),
("mistral.voxtral-mini-3b-2507", model_60),
("mistral.voxtral-small-24b-2507", model_61),
("moonshot.kimi-k2-thinking", model_62),
("moonshotai.kimi-k2.5", model_63),
("nvidia.nemotron-nano-12b-v2", model_64),
("nvidia.nemotron-nano-3-30b", model_65),
("nvidia.nemotron-nano-9b-v2", model_66),
("nvidia.nemotron-super-3-120b", model_67),
("openai.gpt-oss-120b-1:0", model_68),
("openai.gpt-oss-20b-1:0", model_69),
("openai.gpt-oss-safeguard-120b", model_70),
("openai.gpt-oss-safeguard-20b", model_71),
("qwen.qwen3-235b-a22b-2507-v1:0", model_72),
("qwen.qwen3-32b-v1:0", model_73),
("qwen.qwen3-coder-30b-a3b-v1:0", model_74),
("qwen.qwen3-coder-480b-a35b-v1:0", model_75),
("qwen.qwen3-coder-next", model_76),
("qwen.qwen3-next-80b-a3b", model_77),
("qwen.qwen3-vl-235b-a22b", model_78),
("us.anthropic.claude-haiku-4-5-20251001-v1:0", model_79),
("us.anthropic.claude-opus-4-1-20250805-v1:0", model_80),
("us.anthropic.claude-opus-4-20250514-v1:0", model_81),
("us.anthropic.claude-opus-4-5-20251101-v1:0", model_82),
("us.anthropic.claude-opus-4-6-v1", model_83),
("us.anthropic.claude-opus-4-7", model_84),
("us.anthropic.claude-sonnet-4-20250514-v1:0", model_85),
("us.anthropic.claude-sonnet-4-5-20250929-v1:0", model_86),
("us.anthropic.claude-sonnet-4-6", model_87),
("writer.palmyra-x4-v1:0", model_88),
("writer.palmyra-x5-v1:0", model_89),
("zai.glm-4.7", model_90),
("zai.glm-4.7-flash", model_91),
("zai.glm-5", model_92),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
