//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "kimi-for-coding".into(),
name: "Kimi For Coding".into(),
api: "anthropic-messages".into(),
provider: "kimi-coding".into(),
base_url: "https://api.kimi.com/coding".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_768.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "KimiCLI/1.5".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "kimi-k2-thinking".into(),
name: "Kimi K2 Thinking".into(),
api: "anthropic-messages".into(),
provider: "kimi-coding".into(),
base_url: "https://api.kimi.com/coding".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_768.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "KimiCLI/1.5".into())])),
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("kimi-for-coding", model_0),
("kimi-k2-thinking", model_1),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
