//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "MiniMax-M2.7".into(),
name: "MiniMax-M2.7".into(),
api: "anthropic-messages".into(),
provider: "minimax".into(),
base_url: "https://api.minimax.io/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "MiniMax-M2.7-highspeed".into(),
name: "MiniMax-M2.7-highspeed".into(),
api: "anthropic-messages".into(),
provider: "minimax".into(),
base_url: "https://api.minimax.io/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.4, cache_read: 0.06, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("MiniMax-M2.7", model_0),
("MiniMax-M2.7-highspeed", model_1),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
