//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "deepseek-v4-flash".into(),
name: "DeepSeek V4 Flash".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("high".into())),(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.14, output: 0.28, cache_read: 0.0028, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
requires_reasoning_content_on_assistant_messages: Some(true),
thinking_format: Some(crate::ThinkingFormat::Deepseek),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "deepseek-v4-pro".into(),
name: "DeepSeek V4 Pro".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, None),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("high".into())),(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.74, output: 3.48, cache_read: 0.0145, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
requires_reasoning_content_on_assistant_messages: Some(true),
thinking_format: Some(crate::ThinkingFormat::Deepseek),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "glm-5".into(),
name: "GLM-5".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.2, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "glm-5.1".into(),
name: "GLM-5.1".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0 },
context_window: 202_752.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.1, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "kimi-k2.6".into(),
name: "Kimi K2.6 (3x limits)".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.32, output: 1.34, cache_read: 0.054, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "mimo-v2-omni".into(),
name: "MiMo V2 Omni".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "mimo-v2-pro".into(),
name: "MiMo V2 Pro".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "mimo-v2.5".into(),
name: "MiMo V2.5".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "mimo-v2.5-pro".into(),
name: "MiMo V2.5 Pro".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "minimax-m2.5".into(),
name: "MiniMax M2.5".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "minimax-m2.7".into(),
name: "MiniMax M2.7".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "qwen3.5-plus".into(),
name: "Qwen3.5 Plus".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 1.2, cache_read: 0.02, cache_write: 0.25 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
thinking_format: Some(crate::ThinkingFormat::Qwen),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "qwen3.6-plus".into(),
name: "Qwen3.6 Plus".into(),
api: "openai-completions".into(),
provider: "opencode-go".into(),
base_url: "https://opencode.ai/zen/go/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.625 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
thinking_format: Some(crate::ThinkingFormat::Qwen),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("deepseek-v4-flash", model_0),
("deepseek-v4-pro", model_1),
("glm-5", model_2),
("glm-5.1", model_3),
("kimi-k2.5", model_4),
("kimi-k2.6", model_5),
("mimo-v2-omni", model_6),
("mimo-v2-pro", model_7),
("mimo-v2.5", model_8),
("mimo-v2.5-pro", model_9),
("minimax-m2.5", model_10),
("minimax-m2.7", model_11),
("qwen3.5-plus", model_12),
("qwen3.6-plus", model_13),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
