//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "mimo-v2-flash".into(),
name: "MiMo-V2-Flash".into(),
api: "anthropic-messages".into(),
provider: "xiaomi-token-plan-cn".into(),
base_url: "https://token-plan-cn.xiaomimimo.com/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.1, output: 0.3, cache_read: 0.01, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "mimo-v2-omni".into(),
name: "MiMo-V2-Omni".into(),
api: "anthropic-messages".into(),
provider: "xiaomi-token-plan-cn".into(),
base_url: "https://token-plan-cn.xiaomimimo.com/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "mimo-v2-pro".into(),
name: "MiMo-V2-Pro".into(),
api: "anthropic-messages".into(),
provider: "xiaomi-token-plan-cn".into(),
base_url: "https://token-plan-cn.xiaomimimo.com/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "mimo-v2.5".into(),
name: "MiMo-V2.5".into(),
api: "anthropic-messages".into(),
provider: "xiaomi-token-plan-cn".into(),
base_url: "https://token-plan-cn.xiaomimimo.com/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.4, output: 2.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "mimo-v2.5-pro".into(),
name: "MiMo-V2.5-Pro".into(),
api: "anthropic-messages".into(),
provider: "xiaomi-token-plan-cn".into(),
base_url: "https://token-plan-cn.xiaomimimo.com/anthropic".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("mimo-v2-flash", model_0),
("mimo-v2-omni", model_1),
("mimo-v2-pro", model_2),
("mimo-v2.5", model_3),
("mimo-v2.5-pro", model_4),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
