//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "alibaba/qwen-3-14b".into(),
name: "Qwen3-14B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.12, output: 0.24, cache_read: 0.0, cache_write: 0.0 },
context_window: 40_960.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "alibaba/qwen-3-235b".into(),
name: "Qwen3 235B A22b Instruct 2507".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 1.2, cache_read: 0.6, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 40_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "alibaba/qwen-3-30b".into(),
name: "Qwen3-30B-A3B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.08, output: 0.29, cache_read: 0.0, cache_write: 0.0 },
context_window: 40_960.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "alibaba/qwen-3-32b".into(),
name: "Qwen 3 32B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.16, output: 0.64, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "alibaba/qwen-3.6-max-preview".into(),
name: "Qwen 3.6 Max Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.3, output: 7.8, cache_read: 0.26, cache_write: 1.625 },
context_window: 240_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-235b-a22b-thinking".into(),
name: "Qwen3 VL 235B A22B Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 4.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-coder".into(),
name: "Qwen3 Coder 480B A35B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.5, output: 7.5, cache_read: 0.3, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-coder-30b-a3b".into(),
name: "Qwen 3 Coder 30B A3B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-coder-next".into(),
name: "Qwen3 Coder Next".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.5, output: 1.2, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-coder-plus".into(),
name: "Qwen3 Coder Plus".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-max".into(),
name: "Qwen3 Max".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.2, output: 6.0, cache_read: 0.24, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-max-preview".into(),
name: "Qwen3 Max Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.2, output: 6.0, cache_read: 0.24, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-max-thinking".into(),
name: "Qwen 3 Max Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.2, output: 6.0, cache_read: 0.24, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "alibaba/qwen3-vl-thinking".into(),
name: "Qwen3 VL 235B A22B Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 4.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "alibaba/qwen3.5-flash".into(),
name: "Qwen 3.5 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.399_999_999_999_999_97, cache_read: 0.001, cache_write: 0.125 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "alibaba/qwen3.5-plus".into(),
name: "Qwen 3.5 Plus".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 2.4, cache_read: 0.04, cache_write: 0.5 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "alibaba/qwen3.6-27b".into(),
name: "Qwen 3.6 27B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.599_999_999_999_999_6, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "alibaba/qwen3.6-plus".into(),
name: "Qwen 3.6 Plus".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.099_999_999_999_999_99, cache_write: 0.625 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "anthropic/claude-3-haiku".into(),
name: "Claude 3 Haiku".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 1.25, cache_read: 0.03, cache_write: 0.3 },
context_window: 200_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "anthropic/claude-3.5-haiku".into(),
name: "Claude 3.5 Haiku".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.799_999_999_999_999_9, output: 4.0, cache_read: 0.08, cache_write: 1.0 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "anthropic/claude-3.7-sonnet".into(),
name: "Claude 3.7 Sonnet".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "anthropic/claude-haiku-4.5".into(),
name: "Claude Haiku 4.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.099_999_999_999_999_99, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "anthropic/claude-opus-4".into(),
name: "Claude Opus 4".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "anthropic/claude-opus-4.1".into(),
name: "Claude Opus 4.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "anthropic/claude-opus-4.5".into(),
name: "Claude Opus 4.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "anthropic/claude-opus-4.6".into(),
name: "Claude Opus 4.6".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "anthropic/claude-opus-4.7".into(),
name: "Claude Opus 4.7".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_27() -> crate::Model {
crate::Model {
id: "anthropic/claude-sonnet-4".into(),
name: "Claude Sonnet 4".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_28() -> crate::Model {
crate::Model {
id: "anthropic/claude-sonnet-4.5".into(),
name: "Claude Sonnet 4.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_29() -> crate::Model {
crate::Model {
id: "anthropic/claude-sonnet-4.6".into(),
name: "Claude Sonnet 4.6".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_30() -> crate::Model {
crate::Model {
id: "arcee-ai/trinity-large-preview".into(),
name: "Trinity Large Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 1.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_31() -> crate::Model {
crate::Model {
id: "arcee-ai/trinity-large-thinking".into(),
name: "Trinity Large Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 0.899_999_999_999_999_9, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_100.0,
max_tokens: 80_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_32() -> crate::Model {
crate::Model {
id: "bytedance/seed-1.6".into(),
name: "Seed 1.6".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_33() -> crate::Model {
crate::Model {
id: "cohere/command-a".into(),
name: "Command A".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_34() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-r1".into(),
name: "DeepSeek-R1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.35, output: 5.4, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_35() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v3".into(),
name: "DeepSeek V3 0324".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.77, output: 0.77, cache_read: 0.0, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_36() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v3.1".into(),
name: "DeepSeek-V3.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.56, output: 1.68, cache_read: 0.28, cache_write: 0.0 },
context_window: 163_840.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_37() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v3.1-terminus".into(),
name: "DeepSeek V3.1 Terminus".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.27, output: 1.0, cache_read: 0.135, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_38() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v3.2".into(),
name: "DeepSeek V3.2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.28, output: 0.42, cache_read: 0.028, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_39() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v3.2-thinking".into(),
name: "DeepSeek V3.2 Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.62, output: 1.85, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_40() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v4-flash".into(),
name: "DeepSeek V4 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.14, output: 0.28, cache_read: 0.0028, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_41() -> crate::Model {
crate::Model {
id: "deepseek/deepseek-v4-pro".into(),
name: "DeepSeek V4 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.435, output: 0.87, cache_read: 0.0036, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 384_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_42() -> crate::Model {
crate::Model {
id: "google/gemini-2.0-flash".into(),
name: "Gemini 2.0 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.024_999_999_999_999_998, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_43() -> crate::Model {
crate::Model {
id: "google/gemini-2.0-flash-lite".into(),
name: "Gemini 2.0 Flash Lite".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.02, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_44() -> crate::Model {
crate::Model {
id: "google/gemini-2.5-flash".into(),
name: "Gemini 2.5 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 2.5, cache_read: 0.03, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_45() -> crate::Model {
crate::Model {
id: "google/gemini-2.5-flash-lite".into(),
name: "Gemini 2.5 Flash Lite".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.399_999_999_999_999_97, cache_read: 0.01, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_46() -> crate::Model {
crate::Model {
id: "google/gemini-2.5-pro".into(),
name: "Gemini 2.5 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_47() -> crate::Model {
crate::Model {
id: "google/gemini-3-flash".into(),
name: "Gemini 3 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 65_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_48() -> crate::Model {
crate::Model {
id: "google/gemini-3-pro-preview".into(),
name: "Gemini 3 Pro Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_49() -> crate::Model {
crate::Model {
id: "google/gemini-3.1-flash-lite-preview".into(),
name: "Gemini 3.1 Flash Lite Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 1.5, cache_read: 0.03, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 65_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_50() -> crate::Model {
crate::Model {
id: "google/gemini-3.1-pro-preview".into(),
name: "Gemini 3.1 Pro Preview".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_51() -> crate::Model {
crate::Model {
id: "google/gemma-4-26b-a4b-it".into(),
name: "Gemma 4 26B A4B IT".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.13, output: 0.399_999_999_999_999_97, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_52() -> crate::Model {
crate::Model {
id: "google/gemma-4-31b-it".into(),
name: "Gemma 4 31B IT".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.14, output: 0.399_999_999_999_999_97, cache_read: 0.0, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_53() -> crate::Model {
crate::Model {
id: "inception/mercury-2".into(),
name: "Mercury 2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 0.75, cache_read: 0.024_999_999_999_999_998, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_54() -> crate::Model {
crate::Model {
id: "inception/mercury-coder-small".into(),
name: "Mercury Coder Small Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.25, output: 1.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_55() -> crate::Model {
crate::Model {
id: "kwaipilot/kat-coder-pro-v2".into(),
name: "Kat Coder Pro V2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_56() -> crate::Model {
crate::Model {
id: "meituan/longcat-flash-chat".into(),
name: "LongCat Flash Chat".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_57() -> crate::Model {
crate::Model {
id: "meta/llama-3.1-70b".into(),
name: "Llama 3.1 70B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_58() -> crate::Model {
crate::Model {
id: "meta/llama-3.1-8b".into(),
name: "Llama 3.1 8B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.22, output: 0.22, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_59() -> crate::Model {
crate::Model {
id: "meta/llama-3.2-11b".into(),
name: "Llama 3.2 11B Vision Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.16, output: 0.16, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_60() -> crate::Model {
crate::Model {
id: "meta/llama-3.2-90b".into(),
name: "Llama 3.2 90B Vision Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_61() -> crate::Model {
crate::Model {
id: "meta/llama-3.3-70b".into(),
name: "Llama 3.3 70B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.72, output: 0.72, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_62() -> crate::Model {
crate::Model {
id: "meta/llama-4-maverick".into(),
name: "Llama 4 Maverick 17B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.24, output: 0.970_000_000_000_000_1, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_63() -> crate::Model {
crate::Model {
id: "meta/llama-4-scout".into(),
name: "Llama 4 Scout 17B Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.169_999_999_999_999_98, output: 0.66, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_64() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2".into(),
name: "MiniMax M2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.375 },
context_window: 205_000.0,
max_tokens: 205_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_65() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.1".into(),
name: "MiniMax M2.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_66() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.1-lightning".into(),
name: "MiniMax M2.1 Lightning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 2.4, cache_read: 0.03, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_67() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.5".into(),
name: "MiniMax M2.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.03, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_68() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.5-highspeed".into(),
name: "MiniMax M2.5 High Speed".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.4, cache_read: 0.03, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_69() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.7".into(),
name: "Minimax M2.7".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_70() -> crate::Model {
crate::Model {
id: "minimax/minimax-m2.7-highspeed".into(),
name: "MiniMax M2.7 High Speed".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 2.4, cache_read: 0.06, cache_write: 0.375 },
context_window: 204_800.0,
max_tokens: 131_100.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_71() -> crate::Model {
crate::Model {
id: "mistral/codestral".into(),
name: "Mistral Codestral".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 0.899_999_999_999_999_9, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_72() -> crate::Model {
crate::Model {
id: "mistral/devstral-2".into(),
name: "Devstral 2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_73() -> crate::Model {
crate::Model {
id: "mistral/devstral-small".into(),
name: "Devstral Small 1.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_74() -> crate::Model {
crate::Model {
id: "mistral/devstral-small-2".into(),
name: "Devstral Small 2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_75() -> crate::Model {
crate::Model {
id: "mistral/ministral-3b".into(),
name: "Ministral 3B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.099_999_999_999_999_99, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_76() -> crate::Model {
crate::Model {
id: "mistral/ministral-8b".into(),
name: "Ministral 8B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_77() -> crate::Model {
crate::Model {
id: "mistral/mistral-medium".into(),
name: "Mistral Medium 3.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 2.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_78() -> crate::Model {
crate::Model {
id: "mistral/mistral-small".into(),
name: "Mistral Small".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 32_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_79() -> crate::Model {
crate::Model {
id: "mistral/pixtral-12b".into(),
name: "Pixtral 12B 2409".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.15, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_80() -> crate::Model {
crate::Model {
id: "mistral/pixtral-large".into(),
name: "Pixtral Large".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_81() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2".into(),
name: "Kimi K2 Instruct".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.570_000_000_000_000_1, output: 2.3, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_82() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2-thinking".into(),
name: "Kimi K2 Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.5, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_114.0,
max_tokens: 262_114.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_83() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2-thinking-turbo".into(),
name: "Kimi K2 Thinking Turbo".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.15, output: 8.0, cache_read: 0.15, cache_write: 0.0 },
context_window: 262_114.0,
max_tokens: 262_114.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_84() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2-turbo".into(),
name: "Kimi K2 Turbo".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.15, output: 8.0, cache_read: 0.15, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_85() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.099_999_999_999_999_99, cache_write: 0.0 },
context_window: 262_114.0,
max_tokens: 262_114.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_86() -> crate::Model {
crate::Model {
id: "moonshotai/kimi-k2.6".into(),
name: "Kimi K2.6".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 262_000.0,
max_tokens: 262_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_87() -> crate::Model {
crate::Model {
id: "nvidia/nemotron-nano-12b-v2-vl".into(),
name: "Nvidia Nemotron Nano 12B V2 VL".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 0.6, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_88() -> crate::Model {
crate::Model {
id: "nvidia/nemotron-nano-9b-v2".into(),
name: "Nvidia Nemotron Nano 9B V2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.06, output: 0.229_999_999_999_999_98, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_89() -> crate::Model {
crate::Model {
id: "openai/gpt-4-turbo".into(),
name: "GPT-4 Turbo".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 10.0, output: 30.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_90() -> crate::Model {
crate::Model {
id: "openai/gpt-4.1".into(),
name: "GPT-4.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 8.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_91() -> crate::Model {
crate::Model {
id: "openai/gpt-4.1-mini".into(),
name: "GPT-4.1 mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 1.599_999_999_999_999_9, cache_read: 0.099_999_999_999_999_99, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_92() -> crate::Model {
crate::Model {
id: "openai/gpt-4.1-nano".into(),
name: "GPT-4.1 nano".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.399_999_999_999_999_97, cache_read: 0.024_999_999_999_999_998, cache_write: 0.0 },
context_window: 1_047_576.0,
max_tokens: 32_768.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_93() -> crate::Model {
crate::Model {
id: "openai/gpt-4o".into(),
name: "GPT-4o".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 10.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_94() -> crate::Model {
crate::Model {
id: "openai/gpt-4o-mini".into(),
name: "GPT-4o mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.075, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_95() -> crate::Model {
crate::Model {
id: "openai/gpt-5".into(),
name: "GPT-5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_96() -> crate::Model {
crate::Model {
id: "openai/gpt-5-chat".into(),
name: "GPT 5 Chat".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_97() -> crate::Model {
crate::Model {
id: "openai/gpt-5-codex".into(),
name: "GPT-5-Codex".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_98() -> crate::Model {
crate::Model {
id: "openai/gpt-5-mini".into(),
name: "GPT-5 mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.024_999_999_999_999_998, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_99() -> crate::Model {
crate::Model {
id: "openai/gpt-5-nano".into(),
name: "GPT-5 nano".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.049_999_999_999_999_996, output: 0.399_999_999_999_999_97, cache_read: 0.005, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_100() -> crate::Model {
crate::Model {
id: "openai/gpt-5-pro".into(),
name: "GPT-5 pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 120.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 272_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_101() -> crate::Model {
crate::Model {
id: "openai/gpt-5.1-codex".into(),
name: "GPT-5.1-Codex".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_102() -> crate::Model {
crate::Model {
id: "openai/gpt-5.1-codex-max".into(),
name: "GPT 5.1 Codex Max".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_103() -> crate::Model {
crate::Model {
id: "openai/gpt-5.1-codex-mini".into(),
name: "GPT 5.1 Codex Mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.024_999_999_999_999_998, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_104() -> crate::Model {
crate::Model {
id: "openai/gpt-5.1-instant".into(),
name: "GPT-5.1 Instant".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_105() -> crate::Model {
crate::Model {
id: "openai/gpt-5.1-thinking".into(),
name: "GPT 5.1 Thinking".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_106() -> crate::Model {
crate::Model {
id: "openai/gpt-5.2".into(),
name: "GPT 5.2".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_107() -> crate::Model {
crate::Model {
id: "openai/gpt-5.2-chat".into(),
name: "GPT 5.2 Chat".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_108() -> crate::Model {
crate::Model {
id: "openai/gpt-5.2-codex".into(),
name: "GPT 5.2 Codex".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_109() -> crate::Model {
crate::Model {
id: "openai/gpt-5.2-pro".into(),
name: "GPT 5.2 ".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 21.0, output: 168.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_110() -> crate::Model {
crate::Model {
id: "openai/gpt-5.3-chat".into(),
name: "GPT-5.3 Chat".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_111() -> crate::Model {
crate::Model {
id: "openai/gpt-5.3-codex".into(),
name: "GPT 5.3 Codex".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_112() -> crate::Model {
crate::Model {
id: "openai/gpt-5.4".into(),
name: "GPT 5.4".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 15.0, cache_read: 0.25, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_113() -> crate::Model {
crate::Model {
id: "openai/gpt-5.4-mini".into(),
name: "GPT 5.4 Mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.75, output: 4.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_114() -> crate::Model {
crate::Model {
id: "openai/gpt-5.4-nano".into(),
name: "GPT 5.4 Nano".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 1.25, cache_read: 0.02, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_115() -> crate::Model {
crate::Model {
id: "openai/gpt-5.4-pro".into(),
name: "GPT 5.4 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_116() -> crate::Model {
crate::Model {
id: "openai/gpt-5.5".into(),
name: "GPT 5.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 30.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_117() -> crate::Model {
crate::Model {
id: "openai/gpt-5.5-pro".into(),
name: "GPT 5.5 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_118() -> crate::Model {
crate::Model {
id: "openai/gpt-oss-20b".into(),
name: "GPT OSS 120B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.049_999_999_999_999_996, output: 0.199_999_999_999_999_98, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_119() -> crate::Model {
crate::Model {
id: "openai/gpt-oss-safeguard-20b".into(),
name: "GPT OSS Safeguard 20B".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.037, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_120() -> crate::Model {
crate::Model {
id: "openai/o1".into(),
name: "o1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 60.0, cache_read: 7.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_121() -> crate::Model {
crate::Model {
id: "openai/o3".into(),
name: "o3".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 8.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_122() -> crate::Model {
crate::Model {
id: "openai/o3-deep-research".into(),
name: "o3-deep-research".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 10.0, output: 40.0, cache_read: 2.5, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_123() -> crate::Model {
crate::Model {
id: "openai/o3-mini".into(),
name: "o3-mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.1, output: 4.4, cache_read: 0.55, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_124() -> crate::Model {
crate::Model {
id: "openai/o3-pro".into(),
name: "o3 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 20.0, output: 80.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_125() -> crate::Model {
crate::Model {
id: "openai/o4-mini".into(),
name: "o4-mini".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.1, output: 4.4, cache_read: 0.275, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 100_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_126() -> crate::Model {
crate::Model {
id: "perplexity/sonar".into(),
name: "Sonar".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 127_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_127() -> crate::Model {
crate::Model {
id: "perplexity/sonar-pro".into(),
name: "Sonar Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 8000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_128() -> crate::Model {
crate::Model {
id: "xai/grok-3".into(),
name: "Grok 3 Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.75, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_129() -> crate::Model {
crate::Model {
id: "xai/grok-3-fast".into(),
name: "Grok 3 Fast Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_130() -> crate::Model {
crate::Model {
id: "xai/grok-3-mini".into(),
name: "Grok 3 Mini Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 0.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_131() -> crate::Model {
crate::Model {
id: "xai/grok-3-mini-fast".into(),
name: "Grok 3 Mini Fast Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 4.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_132() -> crate::Model {
crate::Model {
id: "xai/grok-4".into(),
name: "Grok 4".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.75, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_133() -> crate::Model {
crate::Model {
id: "xai/grok-4-fast-non-reasoning".into(),
name: "Grok 4 Fast Non-Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 0.5, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_134() -> crate::Model {
crate::Model {
id: "xai/grok-4-fast-reasoning".into(),
name: "Grok 4 Fast Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 0.5, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_135() -> crate::Model {
crate::Model {
id: "xai/grok-4.1-fast-non-reasoning".into(),
name: "Grok 4.1 Fast Non-Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 0.5, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_136() -> crate::Model {
crate::Model {
id: "xai/grok-4.1-fast-reasoning".into(),
name: "Grok 4.1 Fast Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 0.5, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_137() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-multi-agent".into(),
name: "Grok 4.20 Multi-Agent".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_138() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-multi-agent-beta".into(),
name: "Grok 4.20 Multi Agent Beta".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_139() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-non-reasoning".into(),
name: "Grok 4.20 Non-Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_140() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-non-reasoning-beta".into(),
name: "Grok 4.20 Beta Non-Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_141() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-reasoning".into(),
name: "Grok 4.20 Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_142() -> crate::Model {
crate::Model {
id: "xai/grok-4.20-reasoning-beta".into(),
name: "Grok 4.20 Beta Reasoning".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 2_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_143() -> crate::Model {
crate::Model {
id: "xai/grok-4.3".into(),
name: "Grok 4.3".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 2.5, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 1_000_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_144() -> crate::Model {
crate::Model {
id: "xai/grok-code-fast-1".into(),
name: "Grok Code Fast 1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 1.5, cache_read: 0.02, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 256_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_145() -> crate::Model {
crate::Model {
id: "xiaomi/mimo-v2-flash".into(),
name: "MiMo V2 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.099_999_999_999_999_99, output: 0.3, cache_read: 0.01, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_146() -> crate::Model {
crate::Model {
id: "xiaomi/mimo-v2-pro".into(),
name: "MiMo V2 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_147() -> crate::Model {
crate::Model {
id: "xiaomi/mimo-v2.5".into(),
name: "MiMo M2.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.399_999_999_999_999_97, output: 2.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 131_100.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_148() -> crate::Model {
crate::Model {
id: "xiaomi/mimo-v2.5-pro".into(),
name: "MiMo V2.5 Pro".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 3.0, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_149() -> crate::Model {
crate::Model {
id: "zai/glm-4.5".into(),
name: "GLM-4.5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.2, cache_read: 0.11, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 96_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_150() -> crate::Model {
crate::Model {
id: "zai/glm-4.5-air".into(),
name: "GLM 4.5 Air".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.199_999_999_999_999_98, output: 1.1, cache_read: 0.03, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 96_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_151() -> crate::Model {
crate::Model {
id: "zai/glm-4.5v".into(),
name: "GLM 4.5V".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 1.799_999_999_999_999_8, cache_read: 0.11, cache_write: 0.0 },
context_window: 66_000.0,
max_tokens: 16_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_152() -> crate::Model {
crate::Model {
id: "zai/glm-4.6".into(),
name: "GLM 4.6".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 2.2, cache_read: 0.11, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 96_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_153() -> crate::Model {
crate::Model {
id: "zai/glm-4.6v".into(),
name: "GLM-4.6V".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 0.899_999_999_999_999_9, cache_read: 0.049_999_999_999_999_996, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 24_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_154() -> crate::Model {
crate::Model {
id: "zai/glm-4.6v-flash".into(),
name: "GLM-4.6V-Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 24_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_155() -> crate::Model {
crate::Model {
id: "zai/glm-4.7".into(),
name: "GLM 4.7".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.25, output: 2.75, cache_read: 2.25, cache_write: 0.0 },
context_window: 131_000.0,
max_tokens: 40_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_156() -> crate::Model {
crate::Model {
id: "zai/glm-4.7-flash".into(),
name: "GLM 4.7 Flash".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.07, output: 0.399_999_999_999_999_97, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 131_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_157() -> crate::Model {
crate::Model {
id: "zai/glm-4.7-flashx".into(),
name: "GLM 4.7 FlashX".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.06, output: 0.399_999_999_999_999_97, cache_read: 0.01, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_158() -> crate::Model {
crate::Model {
id: "zai/glm-5".into(),
name: "GLM 5".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.199_999_999_999_999_7, cache_read: 0.199_999_999_999_999_98, cache_write: 0.0 },
context_window: 202_800.0,
max_tokens: 131_100.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_159() -> crate::Model {
crate::Model {
id: "zai/glm-5-turbo".into(),
name: "GLM 5 Turbo".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.2, output: 4.0, cache_read: 0.24, cache_write: 0.0 },
context_window: 202_800.0,
max_tokens: 131_100.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_160() -> crate::Model {
crate::Model {
id: "zai/glm-5.1".into(),
name: "GLM 5.1".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0 },
context_window: 202_800.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_161() -> crate::Model {
crate::Model {
id: "zai/glm-5v-turbo".into(),
name: "GLM 5V Turbo".into(),
api: "anthropic-messages".into(),
provider: "vercel-ai-gateway".into(),
base_url: "https://ai-gateway.vercel.sh".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.2, output: 4.0, cache_read: 0.24, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("alibaba/qwen-3-14b", model_0),
("alibaba/qwen-3-235b", model_1),
("alibaba/qwen-3-30b", model_2),
("alibaba/qwen-3-32b", model_3),
("alibaba/qwen-3.6-max-preview", model_4),
("alibaba/qwen3-235b-a22b-thinking", model_5),
("alibaba/qwen3-coder", model_6),
("alibaba/qwen3-coder-30b-a3b", model_7),
("alibaba/qwen3-coder-next", model_8),
("alibaba/qwen3-coder-plus", model_9),
("alibaba/qwen3-max", model_10),
("alibaba/qwen3-max-preview", model_11),
("alibaba/qwen3-max-thinking", model_12),
("alibaba/qwen3-vl-thinking", model_13),
("alibaba/qwen3.5-flash", model_14),
("alibaba/qwen3.5-plus", model_15),
("alibaba/qwen3.6-27b", model_16),
("alibaba/qwen3.6-plus", model_17),
("anthropic/claude-3-haiku", model_18),
("anthropic/claude-3.5-haiku", model_19),
("anthropic/claude-3.7-sonnet", model_20),
("anthropic/claude-haiku-4.5", model_21),
("anthropic/claude-opus-4", model_22),
("anthropic/claude-opus-4.1", model_23),
("anthropic/claude-opus-4.5", model_24),
("anthropic/claude-opus-4.6", model_25),
("anthropic/claude-opus-4.7", model_26),
("anthropic/claude-sonnet-4", model_27),
("anthropic/claude-sonnet-4.5", model_28),
("anthropic/claude-sonnet-4.6", model_29),
("arcee-ai/trinity-large-preview", model_30),
("arcee-ai/trinity-large-thinking", model_31),
("bytedance/seed-1.6", model_32),
("cohere/command-a", model_33),
("deepseek/deepseek-r1", model_34),
("deepseek/deepseek-v3", model_35),
("deepseek/deepseek-v3.1", model_36),
("deepseek/deepseek-v3.1-terminus", model_37),
("deepseek/deepseek-v3.2", model_38),
("deepseek/deepseek-v3.2-thinking", model_39),
("deepseek/deepseek-v4-flash", model_40),
("deepseek/deepseek-v4-pro", model_41),
("google/gemini-2.0-flash", model_42),
("google/gemini-2.0-flash-lite", model_43),
("google/gemini-2.5-flash", model_44),
("google/gemini-2.5-flash-lite", model_45),
("google/gemini-2.5-pro", model_46),
("google/gemini-3-flash", model_47),
("google/gemini-3-pro-preview", model_48),
("google/gemini-3.1-flash-lite-preview", model_49),
("google/gemini-3.1-pro-preview", model_50),
("google/gemma-4-26b-a4b-it", model_51),
("google/gemma-4-31b-it", model_52),
("inception/mercury-2", model_53),
("inception/mercury-coder-small", model_54),
("kwaipilot/kat-coder-pro-v2", model_55),
("meituan/longcat-flash-chat", model_56),
("meta/llama-3.1-70b", model_57),
("meta/llama-3.1-8b", model_58),
("meta/llama-3.2-11b", model_59),
("meta/llama-3.2-90b", model_60),
("meta/llama-3.3-70b", model_61),
("meta/llama-4-maverick", model_62),
("meta/llama-4-scout", model_63),
("minimax/minimax-m2", model_64),
("minimax/minimax-m2.1", model_65),
("minimax/minimax-m2.1-lightning", model_66),
("minimax/minimax-m2.5", model_67),
("minimax/minimax-m2.5-highspeed", model_68),
("minimax/minimax-m2.7", model_69),
("minimax/minimax-m2.7-highspeed", model_70),
("mistral/codestral", model_71),
("mistral/devstral-2", model_72),
("mistral/devstral-small", model_73),
("mistral/devstral-small-2", model_74),
("mistral/ministral-3b", model_75),
("mistral/ministral-8b", model_76),
("mistral/mistral-medium", model_77),
("mistral/mistral-small", model_78),
("mistral/pixtral-12b", model_79),
("mistral/pixtral-large", model_80),
("moonshotai/kimi-k2", model_81),
("moonshotai/kimi-k2-thinking", model_82),
("moonshotai/kimi-k2-thinking-turbo", model_83),
("moonshotai/kimi-k2-turbo", model_84),
("moonshotai/kimi-k2.5", model_85),
("moonshotai/kimi-k2.6", model_86),
("nvidia/nemotron-nano-12b-v2-vl", model_87),
("nvidia/nemotron-nano-9b-v2", model_88),
("openai/gpt-4-turbo", model_89),
("openai/gpt-4.1", model_90),
("openai/gpt-4.1-mini", model_91),
("openai/gpt-4.1-nano", model_92),
("openai/gpt-4o", model_93),
("openai/gpt-4o-mini", model_94),
("openai/gpt-5", model_95),
("openai/gpt-5-chat", model_96),
("openai/gpt-5-codex", model_97),
("openai/gpt-5-mini", model_98),
("openai/gpt-5-nano", model_99),
("openai/gpt-5-pro", model_100),
("openai/gpt-5.1-codex", model_101),
("openai/gpt-5.1-codex-max", model_102),
("openai/gpt-5.1-codex-mini", model_103),
("openai/gpt-5.1-instant", model_104),
("openai/gpt-5.1-thinking", model_105),
("openai/gpt-5.2", model_106),
("openai/gpt-5.2-chat", model_107),
("openai/gpt-5.2-codex", model_108),
("openai/gpt-5.2-pro", model_109),
("openai/gpt-5.3-chat", model_110),
("openai/gpt-5.3-codex", model_111),
("openai/gpt-5.4", model_112),
("openai/gpt-5.4-mini", model_113),
("openai/gpt-5.4-nano", model_114),
("openai/gpt-5.4-pro", model_115),
("openai/gpt-5.5", model_116),
("openai/gpt-5.5-pro", model_117),
("openai/gpt-oss-20b", model_118),
("openai/gpt-oss-safeguard-20b", model_119),
("openai/o1", model_120),
("openai/o3", model_121),
("openai/o3-deep-research", model_122),
("openai/o3-mini", model_123),
("openai/o3-pro", model_124),
("openai/o4-mini", model_125),
("perplexity/sonar", model_126),
("perplexity/sonar-pro", model_127),
("xai/grok-3", model_128),
("xai/grok-3-fast", model_129),
("xai/grok-3-mini", model_130),
("xai/grok-3-mini-fast", model_131),
("xai/grok-4", model_132),
("xai/grok-4-fast-non-reasoning", model_133),
("xai/grok-4-fast-reasoning", model_134),
("xai/grok-4.1-fast-non-reasoning", model_135),
("xai/grok-4.1-fast-reasoning", model_136),
("xai/grok-4.20-multi-agent", model_137),
("xai/grok-4.20-multi-agent-beta", model_138),
("xai/grok-4.20-non-reasoning", model_139),
("xai/grok-4.20-non-reasoning-beta", model_140),
("xai/grok-4.20-reasoning", model_141),
("xai/grok-4.20-reasoning-beta", model_142),
("xai/grok-4.3", model_143),
("xai/grok-code-fast-1", model_144),
("xiaomi/mimo-v2-flash", model_145),
("xiaomi/mimo-v2-pro", model_146),
("xiaomi/mimo-v2.5", model_147),
("xiaomi/mimo-v2.5-pro", model_148),
("zai/glm-4.5", model_149),
("zai/glm-4.5-air", model_150),
("zai/glm-4.5v", model_151),
("zai/glm-4.6", model_152),
("zai/glm-4.6v", model_153),
("zai/glm-4.6v-flash", model_154),
("zai/glm-4.7", model_155),
("zai/glm-4.7-flash", model_156),
("zai/glm-4.7-flashx", model_157),
("zai/glm-5", model_158),
("zai/glm-5-turbo", model_159),
("zai/glm-5.1", model_160),
("zai/glm-5v-turbo", model_161),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
