//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "claude-haiku-4.5".into(),
name: "Claude Haiku 4.5".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 144_000.0,
max_tokens: 32_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::AnthropicMessages(crate::AnthropicMessagesCompat { supports_eager_tool_input_streaming: Some(false), supports_long_cache_retention: None })),
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "claude-opus-4.5".into(),
name: "Claude Opus 4.5".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 160_000.0,
max_tokens: 32_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "claude-opus-4.6".into(),
name: "Claude Opus 4.6".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "claude-opus-4.7".into(),
name: "Claude Opus 4.7".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 144_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "claude-sonnet-4".into(),
name: "Claude Sonnet 4".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 216_000.0,
max_tokens: 16_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::AnthropicMessages(crate::AnthropicMessagesCompat { supports_eager_tool_input_streaming: Some(false), supports_long_cache_retention: None })),
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "claude-sonnet-4.5".into(),
name: "Claude Sonnet 4.5".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 144_000.0,
max_tokens: 32_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::AnthropicMessages(crate::AnthropicMessagesCompat { supports_eager_tool_input_streaming: Some(false), supports_long_cache_retention: None })),
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "claude-sonnet-4.6".into(),
name: "Claude Sonnet 4.6".into(),
api: "anthropic-messages".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 32_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "gemini-2.5-pro".into(),
name: "Gemini 2.5 Pro".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "gemini-3-flash-preview".into(),
name: "Gemini 3 Flash".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gemini-3-pro-preview".into(),
name: "Gemini 3 Pro Preview".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro-preview".into(),
name: "Gemini 3.1 Pro Preview".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "gpt-4.1".into(),
name: "GPT-4.1".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 16_384.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "gpt-4o".into(),
name: "GPT-4o".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 4096.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "gpt-5".into(),
name: "GPT-5".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "gpt-5-mini".into(),
name: "GPT-5-mini".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 264_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "gpt-5.1".into(),
name: "GPT-5.1".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 264_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex".into(),
name: "GPT-5.1-Codex".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-max".into(),
name: "GPT-5.1-Codex-max".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-mini".into(),
name: "GPT-5.1-Codex-mini".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "gpt-5.2".into(),
name: "GPT-5.2".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 264_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "gpt-5.2-codex".into(),
name: "GPT-5.2-Codex".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex".into(),
name: "GPT-5.3-Codex".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "gpt-5.4".into(),
name: "GPT-5.4".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "gpt-5.4-mini".into(),
name: "GPT-5.4 Mini".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "gpt-5.5".into(),
name: "GPT-5.5".into(),
api: "openai-responses".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "grok-code-fast-1".into(),
name: "Grok Code Fast 1".into(),
api: "openai-completions".into(),
provider: "github-copilot".into(),
base_url: "https://api.individual.githubcopilot.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 128_000.0,
max_tokens: 64_000.0,
headers: Some(indexmap::IndexMap::from([("User-Agent".into(), "GitHubCopilotChat/0.35.0".into()),("Editor-Version".into(), "vscode/1.107.0".into()),("Editor-Plugin-Version".into(), "copilot-chat/0.35.0".into()),("Copilot-Integration-Id".into(), "vscode-chat".into())])),
compat: Some(crate::ModelCompat::OpenAICompletions(Box::new(crate::OpenAICompletionsCompat {
supports_store: Some(false),
supports_developer_role: Some(false),
supports_reasoning_effort: Some(false),
..crate::OpenAICompletionsCompat::default()
}))),
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("claude-haiku-4.5", model_0),
("claude-opus-4.5", model_1),
("claude-opus-4.6", model_2),
("claude-opus-4.7", model_3),
("claude-sonnet-4", model_4),
("claude-sonnet-4.5", model_5),
("claude-sonnet-4.6", model_6),
("gemini-2.5-pro", model_7),
("gemini-3-flash-preview", model_8),
("gemini-3-pro-preview", model_9),
("gemini-3.1-pro-preview", model_10),
("gpt-4.1", model_11),
("gpt-4o", model_12),
("gpt-5", model_13),
("gpt-5-mini", model_14),
("gpt-5.1", model_15),
("gpt-5.1-codex", model_16),
("gpt-5.1-codex-max", model_17),
("gpt-5.1-codex-mini", model_18),
("gpt-5.2", model_19),
("gpt-5.2-codex", model_20),
("gpt-5.3-codex", model_21),
("gpt-5.4", model_22),
("gpt-5.4-mini", model_23),
("gpt-5.5", model_24),
("grok-code-fast-1", model_25),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
