//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "big-pickle".into(),
name: "Big Pickle".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 200_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "claude-haiku-4-5".into(),
name: "Claude Haiku 4.5".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.0, output: 5.0, cache_read: 0.1, cache_write: 1.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "claude-opus-4-1".into(),
name: "Claude Opus 4.1".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 15.0, output: 75.0, cache_read: 1.5, cache_write: 18.75 },
context_window: 200_000.0,
max_tokens: 32_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "claude-opus-4-5".into(),
name: "Claude Opus 4.5".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "claude-opus-4-6".into(),
name: "Claude Opus 4.6".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("max".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "claude-opus-4-7".into(),
name: "Claude Opus 4.7".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 0.5, cache_write: 6.25 },
context_window: 1_000_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "claude-sonnet-4".into(),
name: "Claude Sonnet 4".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-5".into(),
name: "Claude Sonnet 4.5".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 200_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "claude-sonnet-4-6".into(),
name: "Claude Sonnet 4.6".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.3, cache_write: 3.75 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gemini-3-flash".into(),
name: "Gemini 3 Flash".into(),
api: "google-generative-ai".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro".into(),
name: "Gemini 3.1 Pro Preview".into(),
api: "google-generative-ai".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "glm-5".into(),
name: "GLM-5".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.0, output: 3.2, cache_read: 0.2, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "glm-5.1".into(),
name: "GLM-5.1".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 1.4, output: 4.4, cache_read: 0.26, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "gpt-5".into(),
name: "GPT-5".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.07, output: 8.5, cache_read: 0.107, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "gpt-5-codex".into(),
name: "GPT-5 Codex".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.07, output: 8.5, cache_read: 0.107, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "gpt-5-nano".into(),
name: "GPT-5 Nano".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "gpt-5.1".into(),
name: "GPT-5.1".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.07, output: 8.5, cache_read: 0.107, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex".into(),
name: "GPT-5.1 Codex".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.07, output: 8.5, cache_read: 0.107, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-max".into(),
name: "GPT-5.1 Codex Max".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "gpt-5.1-codex-mini".into(),
name: "GPT-5.1 Codex Mini".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.25, output: 2.0, cache_read: 0.025, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "gpt-5.2".into(),
name: "GPT-5.2".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "gpt-5.2-codex".into(),
name: "GPT-5.2 Codex".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "gpt-5.3-codex".into(),
name: "GPT-5.3 Codex".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.75, output: 14.0, cache_read: 0.175, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "gpt-5.4".into(),
name: "GPT-5.4".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.5, output: 15.0, cache_read: 0.25, cache_write: 0.0 },
context_window: 272_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "gpt-5.4-mini".into(),
name: "GPT-5.4 Mini".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.75, output: 4.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_25() -> crate::Model {
crate::Model {
id: "gpt-5.4-nano".into(),
name: "GPT-5.4 Nano".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 1.25, cache_read: 0.02, cache_write: 0.0 },
context_window: 400_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_26() -> crate::Model {
crate::Model {
id: "gpt-5.4-pro".into(),
name: "GPT-5.4 Pro".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 30.0, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_27() -> crate::Model {
crate::Model {
id: "gpt-5.5".into(),
name: "GPT-5.5".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 30.0, cache_read: 0.5, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_28() -> crate::Model {
crate::Model {
id: "gpt-5.5-pro".into(),
name: "GPT-5.5 Pro".into(),
api: "openai-responses".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Xhigh, Some("xhigh".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 30.0, output: 180.0, cache_read: 30.0, cache_write: 0.0 },
context_window: 1_050_000.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_29() -> crate::Model {
crate::Model {
id: "hy3-preview-free".into(),
name: "Hy3 preview Free".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_30() -> crate::Model {
crate::Model {
id: "kimi-k2.5".into(),
name: "Kimi K2.5".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.6, output: 3.0, cache_read: 0.08, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_31() -> crate::Model {
crate::Model {
id: "kimi-k2.6".into(),
name: "Kimi K2.6".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.95, output: 4.0, cache_read: 0.16, cache_write: 0.0 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_32() -> crate::Model {
crate::Model {
id: "minimax-m2.5".into(),
name: "MiniMax M2.5".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_33() -> crate::Model {
crate::Model {
id: "minimax-m2.5-free".into(),
name: "MiniMax M2.5 Free".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_34() -> crate::Model {
crate::Model {
id: "minimax-m2.7".into(),
name: "MiniMax M2.7".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 1.2, cache_read: 0.06, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 131_072.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_35() -> crate::Model {
crate::Model {
id: "nemotron-3-super-free".into(),
name: "Nemotron 3 Super Free".into(),
api: "openai-completions".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.0, output: 0.0, cache_read: 0.0, cache_write: 0.0 },
context_window: 204_800.0,
max_tokens: 128_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_36() -> crate::Model {
crate::Model {
id: "qwen3.5-plus".into(),
name: "Qwen3.5 Plus".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 1.2, cache_read: 0.02, cache_write: 0.25 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_37() -> crate::Model {
crate::Model {
id: "qwen3.6-plus".into(),
name: "Qwen3.6 Plus".into(),
api: "anthropic-messages".into(),
provider: "opencode".into(),
base_url: "https://opencode.ai/zen".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.625 },
context_window: 262_144.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("big-pickle", model_0),
("claude-haiku-4-5", model_1),
("claude-opus-4-1", model_2),
("claude-opus-4-5", model_3),
("claude-opus-4-6", model_4),
("claude-opus-4-7", model_5),
("claude-sonnet-4", model_6),
("claude-sonnet-4-5", model_7),
("claude-sonnet-4-6", model_8),
("gemini-3-flash", model_9),
("gemini-3.1-pro", model_10),
("glm-5", model_11),
("glm-5.1", model_12),
("gpt-5", model_13),
("gpt-5-codex", model_14),
("gpt-5-nano", model_15),
("gpt-5.1", model_16),
("gpt-5.1-codex", model_17),
("gpt-5.1-codex-max", model_18),
("gpt-5.1-codex-mini", model_19),
("gpt-5.2", model_20),
("gpt-5.2-codex", model_21),
("gpt-5.3-codex", model_22),
("gpt-5.4", model_23),
("gpt-5.4-mini", model_24),
("gpt-5.4-nano", model_25),
("gpt-5.4-pro", model_26),
("gpt-5.5", model_27),
("gpt-5.5-pro", model_28),
("hy3-preview-free", model_29),
("kimi-k2.5", model_30),
("kimi-k2.6", model_31),
("minimax-m2.5", model_32),
("minimax-m2.5-free", model_33),
("minimax-m2.7", model_34),
("nemotron-3-super-free", model_35),
("qwen3.5-plus", model_36),
("qwen3.6-plus", model_37),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
