//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "gemini-1.5-flash".into(),
name: "Gemini 1.5 Flash (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.018_75, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "gemini-1.5-flash-8b".into(),
name: "Gemini 1.5 Flash-8B (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.0375, output: 0.15, cache_read: 0.01, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "gemini-1.5-pro".into(),
name: "Gemini 1.5 Pro (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 5.0, cache_read: 0.3125, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "gemini-2.0-flash".into(),
name: "Gemini 2.0 Flash (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.15, output: 0.6, cache_read: 0.0375, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "gemini-2.0-flash-lite".into(),
name: "Gemini 2.0 Flash Lite (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.075, output: 0.3, cache_read: 0.018_75, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash".into(),
name: "Gemini 2.5 Flash (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.3, output: 2.5, cache_read: 0.03, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-lite".into(),
name: "Gemini 2.5 Flash Lite (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.01, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "gemini-2.5-flash-lite-preview-09-2025".into(),
name: "Gemini 2.5 Flash Lite Preview 09-25 (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.1, output: 0.4, cache_read: 0.01, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "gemini-2.5-pro".into(),
name: "Gemini 2.5 Pro (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 10.0, cache_read: 0.125, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "gemini-3-flash-preview".into(),
name: "Gemini 3 Flash Preview (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None)])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.5, output: 3.0, cache_read: 0.05, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "gemini-3-pro-preview".into(),
name: "Gemini 3 Pro Preview (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro-preview".into(),
name: "Gemini 3.1 Pro Preview (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "gemini-3.1-pro-preview-customtools".into(),
name: "Gemini 3.1 Pro Preview Custom Tools (Vertex)".into(),
api: "google-vertex".into(),
provider: "google-vertex".into(),
base_url: "https://{location}-aiplatform.googleapis.com".into(),
reasoning: true,
thinking_level_map: Some(std::collections::BTreeMap::from([(crate::ModelThinkingLevel::Off, None),(crate::ModelThinkingLevel::Minimal, None),(crate::ModelThinkingLevel::Low, Some("LOW".into())),(crate::ModelThinkingLevel::Medium, None),(crate::ModelThinkingLevel::High, Some("HIGH".into()))])),
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 12.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_048_576.0,
max_tokens: 65_536.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("gemini-1.5-flash", model_0),
("gemini-1.5-flash-8b", model_1),
("gemini-1.5-pro", model_2),
("gemini-2.0-flash", model_3),
("gemini-2.0-flash-lite", model_4),
("gemini-2.5-flash", model_5),
("gemini-2.5-flash-lite", model_6),
("gemini-2.5-flash-lite-preview-09-2025", model_7),
("gemini-2.5-pro", model_8),
("gemini-3-flash-preview", model_9),
("gemini-3-pro-preview", model_10),
("gemini-3.1-pro-preview", model_11),
("gemini-3.1-pro-preview-customtools", model_12),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
