//! Generated by the generate_catalog_data example.
//! Do not edit manually; run `just models-generate` to update.
/// Construct a model descriptor.
fn model_0() -> crate::Model {
crate::Model {
id: "grok-2".into(),
name: "Grok 2".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_1() -> crate::Model {
crate::Model {
id: "grok-2-1212".into(),
name: "Grok 2 (1212)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_2() -> crate::Model {
crate::Model {
id: "grok-2-latest".into(),
name: "Grok 2 Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_3() -> crate::Model {
crate::Model {
id: "grok-2-vision".into(),
name: "Grok 2 Vision".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_4() -> crate::Model {
crate::Model {
id: "grok-2-vision-1212".into(),
name: "Grok 2 Vision (1212)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_5() -> crate::Model {
crate::Model {
id: "grok-2-vision-latest".into(),
name: "Grok 2 Vision Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 10.0, cache_read: 2.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_6() -> crate::Model {
crate::Model {
id: "grok-3".into(),
name: "Grok 3".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.75, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_7() -> crate::Model {
crate::Model {
id: "grok-3-fast".into(),
name: "Grok 3 Fast".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_8() -> crate::Model {
crate::Model {
id: "grok-3-fast-latest".into(),
name: "Grok 3 Fast Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 5.0, output: 25.0, cache_read: 1.25, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_9() -> crate::Model {
crate::Model {
id: "grok-3-latest".into(),
name: "Grok 3 Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.75, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_10() -> crate::Model {
crate::Model {
id: "grok-3-mini".into(),
name: "Grok 3 Mini".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 0.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_11() -> crate::Model {
crate::Model {
id: "grok-3-mini-fast".into(),
name: "Grok 3 Mini Fast".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 4.0, cache_read: 0.15, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_12() -> crate::Model {
crate::Model {
id: "grok-3-mini-fast-latest".into(),
name: "Grok 3 Mini Fast Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.6, output: 4.0, cache_read: 0.15, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_13() -> crate::Model {
crate::Model {
id: "grok-3-mini-latest".into(),
name: "Grok 3 Mini Latest".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.3, output: 0.5, cache_read: 0.075, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 8192.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_14() -> crate::Model {
crate::Model {
id: "grok-4".into(),
name: "Grok 4".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 3.0, output: 15.0, cache_read: 0.75, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 64_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_15() -> crate::Model {
crate::Model {
id: "grok-4-1-fast".into(),
name: "Grok 4.1 Fast".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.5, cache_read: 0.05, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_16() -> crate::Model {
crate::Model {
id: "grok-4-1-fast-non-reasoning".into(),
name: "Grok 4.1 Fast (Non-Reasoning)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.5, cache_read: 0.05, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_17() -> crate::Model {
crate::Model {
id: "grok-4-fast".into(),
name: "Grok 4 Fast".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.5, cache_read: 0.05, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_18() -> crate::Model {
crate::Model {
id: "grok-4-fast-non-reasoning".into(),
name: "Grok 4 Fast (Non-Reasoning)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 0.2, output: 0.5, cache_read: 0.05, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_19() -> crate::Model {
crate::Model {
id: "grok-4.20-0309-non-reasoning".into(),
name: "Grok 4.20 (Non-Reasoning)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_20() -> crate::Model {
crate::Model {
id: "grok-4.20-0309-reasoning".into(),
name: "Grok 4.20 (Reasoning)".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 2.0, output: 6.0, cache_read: 0.2, cache_write: 0.0 },
context_window: 2_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_21() -> crate::Model {
crate::Model {
id: "grok-4.3".into(),
name: "Grok 4.3".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 1.25, output: 2.5, cache_read: 0.2, cache_write: 0.0 },
context_window: 1_000_000.0,
max_tokens: 30_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_22() -> crate::Model {
crate::Model {
id: "grok-beta".into(),
name: "Grok Beta".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 5.0, output: 15.0, cache_read: 5.0, cache_write: 0.0 },
context_window: 131_072.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_23() -> crate::Model {
crate::Model {
id: "grok-code-fast-1".into(),
name: "Grok Code Fast 1".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: true,
thinking_level_map: None,
input: vec![crate::ModelInput::Text],
cost: crate::ModelCost { input: 0.2, output: 1.5, cache_read: 0.02, cache_write: 0.0 },
context_window: 256_000.0,
max_tokens: 10_000.0,
headers: None,
compat: None,
}
}
/// Construct a model descriptor.
fn model_24() -> crate::Model {
crate::Model {
id: "grok-vision-beta".into(),
name: "Grok Vision Beta".into(),
api: "openai-completions".into(),
provider: "xai".into(),
base_url: "https://api.x.ai/v1".into(),
reasoning: false,
thinking_level_map: None,
input: vec![crate::ModelInput::Text,crate::ModelInput::Image],
cost: crate::ModelCost { input: 5.0, output: 15.0, cache_read: 5.0, cache_write: 0.0 },
context_window: 8192.0,
max_tokens: 4096.0,
headers: None,
compat: None,
}
}
/// Construct one model descriptor.
type ModelConstructor = fn() -> crate::Model;
/// Model constructor table in emitted order.
const MODELS: &[(&str, ModelConstructor)] = &[
("grok-2", model_0),
("grok-2-1212", model_1),
("grok-2-latest", model_2),
("grok-2-vision", model_3),
("grok-2-vision-1212", model_4),
("grok-2-vision-latest", model_5),
("grok-3", model_6),
("grok-3-fast", model_7),
("grok-3-fast-latest", model_8),
("grok-3-latest", model_9),
("grok-3-mini", model_10),
("grok-3-mini-fast", model_11),
("grok-3-mini-fast-latest", model_12),
("grok-3-mini-latest", model_13),
("grok-4", model_14),
("grok-4-1-fast", model_15),
("grok-4-1-fast-non-reasoning", model_16),
("grok-4-fast", model_17),
("grok-4-fast-non-reasoning", model_18),
("grok-4.20-0309-non-reasoning", model_19),
("grok-4.20-0309-reasoning", model_20),
("grok-4.3", model_21),
("grok-beta", model_22),
("grok-code-fast-1", model_23),
("grok-vision-beta", model_24),
];
/// Assemble this provider's models in emitted order.
pub(super) fn models() -> indexmap::IndexMap<&'static str, crate::Model> {
MODELS.iter().map(|(key, constructor)| (*key, constructor())).collect()
}
