// Generated model descriptor data.

use crate::Model;
use indexmap::IndexMap;
mod ai21_jamba_large_1_7;
mod alibaba_tongyi_deepresearch_30b_a3b;
mod allenai_olmo_3_1_32b_instruct;
mod amazon_nova_2_lite_v1;
mod anthropic_claude_3_haiku;
mod anthropic_claude_haiku_latest;
mod anthropic_claude_opus_4_7;
mod arcee_ai_trinity_large_preview;
mod auto;
mod baidu_ernie_4_5_21b_a3b;
mod bytedance_seed_seed_1_6;
mod cohere_command_r_08_2024;
mod deepseek_deepseek_chat;
mod essentialai_rnj_1_instruct;
mod google_gemini_2_0_flash_001;
mod google_gemini_3_1_pro_preview;
mod google_gemini_flash_latest;
mod ibm_granite_granite_4_1_8b;
mod inception_mercury_2;
mod inclusionai_ling_2_6_1t_free;
mod kwaipilot_kat_coder_pro_v2;
mod meta_llama_llama_3_8b_instruct;
mod minimax_minimax_m1;
mod mistralai_codestral_2508;
mod mistralai_mistral_large_2512;
mod mistralai_voxtral_small_24b_2507;
mod moonshotai_kimi_k2;
mod moonshotai_kimi_latest;
mod nex_agi_deepseek_v3_1_nex_n1;
mod nvidia_llama_3_1_nemotron_70b_instruct;
mod openai_gpt_3_5_turbo;
mod openai_gpt_4_1_nano;
mod openai_gpt_5_2_codex;
mod openai_gpt_5_mini;
mod openai_gpt_audio;
mod openai_gpt_latest;
mod openai_o3_mini;
mod openrouter_auto;
mod poolside_laguna_m_1_free;
mod prime_intellect_intellect_3;
mod qwen_qwen3_235b_a22b_2507;
mod qwen_qwen3_5_flash_02_23;
mod qwen_qwen3_coder_next;
mod qwen_qwen3_vl_30b_a3b_instruct;
mod qwen_qwen_2_5_72b_instruct;
mod rekaai_reka_edge;
mod relace_relace_search;
mod sao10k_l3_euryale_70b;
mod stepfun_step_3_5_flash;
mod tencent_hy3_preview_free;
mod thedrummer_rocinante_12b;
mod tngtech_deepseek_r1t2_chimera;
mod upstage_solar_pro_3;
mod x_ai_grok_3;
mod xiaomi_mimo_v2_flash;
mod z_ai_glm_4_32b;
mod z_ai_glm_5_turbo;
pub(super) fn models() -> IndexMap<&'static str, Model> {
    let mut models: IndexMap<_, _> = ai21_jamba_large_1_7::models().into();
    models.extend(alibaba_tongyi_deepresearch_30b_a3b::models());
    models.extend(allenai_olmo_3_1_32b_instruct::models());
    models.extend(amazon_nova_2_lite_v1::models());
    models.extend(anthropic_claude_3_haiku::models());
    models.extend(anthropic_claude_opus_4_7::models());
    models.extend(arcee_ai_trinity_large_preview::models());
    models.extend(auto::models());
    models.extend(baidu_ernie_4_5_21b_a3b::models());
    models.extend(bytedance_seed_seed_1_6::models());
    models.extend(cohere_command_r_08_2024::models());
    models.extend(deepseek_deepseek_chat::models());
    models.extend(essentialai_rnj_1_instruct::models());
    models.extend(google_gemini_2_0_flash_001::models());
    models.extend(google_gemini_3_1_pro_preview::models());
    models.extend(ibm_granite_granite_4_1_8b::models());
    models.extend(inception_mercury_2::models());
    models.extend(inclusionai_ling_2_6_1t_free::models());
    models.extend(kwaipilot_kat_coder_pro_v2::models());
    models.extend(meta_llama_llama_3_8b_instruct::models());
    models.extend(minimax_minimax_m1::models());
    models.extend(mistralai_codestral_2508::models());
    models.extend(mistralai_mistral_large_2512::models());
    models.extend(mistralai_voxtral_small_24b_2507::models());
    models.extend(moonshotai_kimi_k2::models());
    models.extend(nex_agi_deepseek_v3_1_nex_n1::models());
    models.extend(nvidia_llama_3_1_nemotron_70b_instruct::models());
    models.extend(openai_gpt_3_5_turbo::models());
    models.extend(openai_gpt_4_1_nano::models());
    models.extend(openai_gpt_5_mini::models());
    models.extend(openai_gpt_5_2_codex::models());
    models.extend(openai_gpt_audio::models());
    models.extend(openai_o3_mini::models());
    models.extend(openrouter_auto::models());
    models.extend(poolside_laguna_m_1_free::models());
    models.extend(prime_intellect_intellect_3::models());
    models.extend(qwen_qwen_2_5_72b_instruct::models());
    models.extend(qwen_qwen3_235b_a22b_2507::models());
    models.extend(qwen_qwen3_coder_next::models());
    models.extend(qwen_qwen3_vl_30b_a3b_instruct::models());
    models.extend(qwen_qwen3_5_flash_02_23::models());
    models.extend(rekaai_reka_edge::models());
    models.extend(relace_relace_search::models());
    models.extend(sao10k_l3_euryale_70b::models());
    models.extend(stepfun_step_3_5_flash::models());
    models.extend(tencent_hy3_preview_free::models());
    models.extend(thedrummer_rocinante_12b::models());
    models.extend(tngtech_deepseek_r1t2_chimera::models());
    models.extend(upstage_solar_pro_3::models());
    models.extend(x_ai_grok_3::models());
    models.extend(xiaomi_mimo_v2_flash::models());
    models.extend(z_ai_glm_4_32b::models());
    models.extend(z_ai_glm_5_turbo::models());
    models.extend(anthropic_claude_haiku_latest::models());
    models.extend(google_gemini_flash_latest::models());
    models.extend(moonshotai_kimi_latest::models());
    models.extend(openai_gpt_latest::models());
    models
}
