// Generated model descriptor data.

use crate::Model;
use indexmap::IndexMap;
mod ai21;
mod alibaba;
mod allenai;
mod amazon;
mod anthropic;
mod arcee_ai;
mod auto;
mod baidu;
mod bytedance_seed;
mod cohere;
mod deepseek;
mod essentialai;
mod google_1;
mod google_2;
mod ibm_granite;
mod inception;
mod inclusionai;
mod kwaipilot;
mod meta_llama;
mod minimax;
mod mistralai_1;
mod mistralai_2;
mod moonshotai;
mod nex_agi;
mod nvidia;
mod openai_1;
mod openai_2;
mod openai_3;
#[path = "openrouter.rs"]
mod openrouter_data;
mod poolside;
mod prime_intellect;
mod qwen_1;
mod qwen_2;
mod qwen_3;
mod rekaai;
mod relace;
mod sao10k;
mod stepfun;
mod tencent;
mod thedrummer;
mod tngtech;
mod upstage;
mod x_ai;
mod xiaomi;
mod z_ai;
pub(super) fn models() -> IndexMap<&'static str, Model> {
    let mut models = IndexMap::new();
    append_1(&mut models);
    append_2(&mut models);
    models
}
fn append_1(models: &mut IndexMap<&'static str, Model>) {
    models.extend(ai21::models_0());
    models.extend(alibaba::models_1());
    models.extend(allenai::models_2());
    models.extend(amazon::models_3());
    models.extend(anthropic::models_8());
    models.extend(anthropic::models_18());
    models.extend(arcee_ai::models_22());
    models.extend(auto::models_26());
    models.extend(baidu::models_27());
    models.extend(bytedance_seed::models_29());
    models.extend(cohere::models_33());
    models.extend(deepseek::models_35());
    models.extend(essentialai::models_45());
    models.extend(google_1::models_46());
    models.extend(google_1::models_56());
    models.extend(ibm_granite::models_64());
    models.extend(inception::models_65());
    models.extend(inclusionai::models_66());
    models.extend(kwaipilot::models_68());
    models.extend(meta_llama::models_69());
    models.extend(minimax::models_75());
    models.extend(mistralai_1::models_81());
    models.extend(mistralai_1::models_91());
    models.extend(mistralai_2::models_100());
    models.extend(moonshotai::models_102());
    models.extend(nex_agi::models_107());
    models.extend(nvidia::models_108());
    models.extend(openai_1::models_118());
    models.extend(openai_1::models_128());
    models.extend(openai_2::models_138());
    models.extend(openai_2::models_148());
    models.extend(openai_3::models_158());
    models.extend(openai_3::models_168());
    models.extend(openrouter_data::models_174());
    models.extend(poolside::models_177());
    models.extend(prime_intellect::models_179());
    models.extend(qwen_1::models_180());
    models.extend(qwen_1::models_190());
    models.extend(qwen_2::models_199());
    models.extend(qwen_2::models_209());
    models.extend(qwen_3::models_218());
    models.extend(rekaai::models_228());
    models.extend(relace::models_229());
    models.extend(sao10k::models_230());
    models.extend(stepfun::models_232());
    models.extend(tencent::models_233());
    models.extend(thedrummer::models_234());
    models.extend(tngtech::models_236());
    models.extend(upstage::models_237());
    models.extend(x_ai::models_238());
}
fn append_2(models: &mut IndexMap<&'static str, Model>) {
    models.extend(xiaomi::models_248());
    models.extend(z_ai::models_253());
    models.extend(z_ai::models_263());
    models.extend(anthropic::models_266());
    models.extend(google_1::models_269());
    models.extend(google_2::models_270());
    models.extend(moonshotai::models_271());
    models.extend(openai_3::models_272());
}
