[package]
name = "maestro-resources"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
maestro-request = { path = "../maestro-request" }
maestro-path = { path = "../maestro-path" }
num-bigint.workspace = true
num-traits.workspace = true
ignore.workspace = true
yaml-rust2.workspace = true
ryu-js.workspace = true

[lints]
workspace = true
